<?php
/**
 * Retailplace_Insider
 *
 * @copyright   Copyright © 2022 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author      Evgeniy Derevyanko <evgeniy@tradesquare.com.au>
 */
/** @var $block \Retailplace\Insider\Block\InsiderObject */
?>
<?php if (!empty($block->getCustomConfig())): ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "Retailplace_Insider/js/insiderObject": <?= $block->jsonSerialize($block->getCustomConfig()) ?>
        }
    }
    </script>
<?php endif ?>
