<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog available for to get notification
 *
 * @var $block \Magefan\Blog\Block\Adminhtml\CheckEnableInfo
 */
?>
<?php if (!$block->isEnabled()) { ?>
    <div class="messages">
        <div class="message message-error">
            <div data-ui-id="messages-message-error">
                <?php $html = __('Magefan Cms Display Rules is disabled, to enable the extension please navigate to 
                <a href="%1" target="_blank">Stores > Configuration > Magefan Extensions > Cms Display Rules</a>.
                ', $block->getUrl('adminhtml/system_config/edit', ['section' => 'mfcmsdisplayrules']));
                ?>
                <?= /**@noEscape**/ $html ?>
            </div>
        </div>
    </div>
<?php } ?>