<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>

<ol class="items">
    <?php foreach ($filterItems as $filterItem) : ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0) : ?>
                <?php
                $attributeCode = '';
                $attributemode = $filterItem['filter']['attribute_model'];
                ?>
                <?php if ($attributemode): ?>
                    <?php $attributeCode = $attributemode->getAttributeCode(); ?>
                <?php endif; ?>
                <?php if ($attributeCode == 'made_in_au' || $attributeCode == 'designed_in_au' || $attributeCode == 'agha_member'): ?>
                    <?php if ($filterItem->getLabel() == "Yes"): ?>
                        <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">
                            <?php if ($attributeCode == 'made_in_au'): ?>
                                <?= __('Made In AU') ?>
                            <?php elseif ($attributeCode == 'designed_in_au'): ?>
                                <?= __('Designed In AU') ?>
                            <?php elseif ($attributeCode == 'agha_member'): ?>
                                <?= __('AGHA Member') ?>
                            <?php else: ?>
                            <?php endif; ?>
                            <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                                <span class="count"><?= /* @noEscape */
                                    (int) $filterItem->getCount() ?><span class="filter-count-label">
                                    <?php if ($filterItem->getCount() == 1) :
                                        ?> <?= $block->escapeHtml(__('item')) ?><?php
                                    else :
                                        ?> <?= $block->escapeHtml(__('item')) ?><?php
                                    endif; ?></span></span>
                            <?php endif; ?>
                        </a>
                    <?php endif; ?>

                <?php else: ?>
                    <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">
                        <!-- <? //= /* @noEscape */ $filterItem->getLabel() ?> -->
                        <?= /* @noEscape */
                        ucfirst($filterItem->getLabel()); ?>
                        <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                            <span class="count"><?= /* @noEscape */
                                (int) $filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1) :
                                ?> <?= $block->escapeHtml(__('item')) ?><?php
                            else :
                                ?> <?= $block->escapeHtml(__('item')) ?><?php
                            endif; ?></span></span>
                        <?php endif; ?>
                    </a>
                <?php endif; ?>

            <?php else : ?>
                <?= /* @noEscape */
                $filterItem->getLabel() ?>
                <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                    <span class="count"><?= /* @noEscape */
                        (int) $filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1) :
                            ?><?= $block->escapeHtml(__('items')) ?><?php
                        else :
                            ?><?= $block->escapeHtml(__('items')) ?><?php
                        endif; ?></span></span>
                <?php endif; ?>
            <?php endif; ?>

        </li>
    <?php endforeach ?>
</ol>
