<?php
/**
 * Mirakl_FrontendDemo
 *
 * @copyright   Copyright (c) 2022 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author      Kirill Kosonogov <kirill.kosonogov@tradesquare.com.au>
 */
/**
 * @var \Mirakl\FrontendDemo\Block\Cart\Item\Shipping $block
 */
?>
<tr>
    <td>
        <span class="checkout-one-brand">
            <a class="quote-request-disabled" href="#">
                <?= __('Buy from this supplier') ?>
            </a>
        </span>
    </td>
</tr>
