<?php
/** @var $block \Magento\Customer\Block\Account\Dashboard\Info */
?>
<div class="did-you-know" id="did-you-know">
    <div class="icon">
        <img src='<?php echo $block->getViewFileUrl('Retailplace_CustomerAccount::images/info.png'); ?>' alt="icon">
    </div>
    <div class="you-know-wrap">
        <div class="you-know-content">
            <h2><?php echo __('Did you know?'); ?></h2>
            <div class="message">
                <span class="register" style="display: none"><?php echo __('Shop over 100,000+ products from 400+ Australian Wholesalers. One login - it\'s that simple.'); ?></span>
                <span class="business_info" style="display: none"><?php echo __('Get the products your business needs right now, and pay later with Zip Business.'); ?></span>
                <span class="preferences" style="display: none"><?php echo __('Buyer\'s Agent service: Let us do the leg work. We will help you find the right products at the right prices.'); ?></span>
                <span class="finish" style="display: none"><?php echo __('Find an identical product listed and we will match it with our 100% price guarantee.'); ?></span>
            </div>
        </div>
    </div>
</div>
