<?php
/**
 * @category   Retailplace
 * @package    Retailplace_Landingpage
 * @author     ishvarmagento@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Retailplace\Landingpage\Controller\Index;

use Magento\Framework\App\Action\Context;
use Retailplace\Landingpage\Model\LandingpageFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Landingpage
     */
    protected $_landingpage;

    public function __construct(
		Context $context,
        LandingpageFactory $landingpage
    ) {
        $this->_landingpage = $landingpage;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$landingpage = $this->_landingpage->create();
        $landingpage->setData($data);
        if($landingpage->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('landingpage/index/index');
        return $resultRedirect;
    }
}
