<?php
/** @var \Retailplace\CustomerAccount\Block\Address $block */
/** @var $countryViewModel \Retailplace\CustomerAccount\ViewModel\Country */

$countryViewModel = $block->getViewModel();
$shippingAddress = $block->getDefaultShippingAddress();
$city = null;
$postCode = null;
$regionId = 0;
$region = null;
$street = [];
$addressId = null;
if ($shippingAddress) {
    $addressId = $shippingAddress->getId();
    $city = $shippingAddress->getCity();
    $postCode = $shippingAddress->getPostcode();
    $regionId = $shippingAddress->getRegionId();
    $street = $shippingAddress->getStreet();
}
?>
<div class="field address">
    <label for="street" class="label">
        <span><?= $block->escapeHtml(__('Start typing your home address')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="street" class="<?= !($shippingAddress) ? 'required' : ''?>" id="street" title="<?= $block->escapeHtmlAttr(__('Business address')) ?>" placeholder="<?= $block->escapeHtml(__('Business address')) ?>">
    </div>
</div>
<?php if (!$shippingAddress) : ?>
<div class="link-enter-address-wrap">
    <span class="link-enter-address" id="link-enter-address"><?= __('Enter address manually') ?></span>
</div>
<?php endif; ?>
<div class="enter-address-wrap" id="enter-address-wrap" <?php if (!$shippingAddress): ?>style="display: none;" <?php endif;?>>
    <div class="enter-address-content">
        <div class="field country required">
            <label for="country" class="label"><span><?= /* @noEscape */ __('Country') ?></span></label>
            <div class="control">
                <?= $countryViewModel->getCountryHtmlSelect(); ?>
            </div>
        </div>
        <div class="field city required">
            <label for="city" class="label">
                <span><?= $block->escapeHtml(__('City')) ?></span>
            </label>
            <div class="control">
                <input type="text" value="<?= $block->escapeHtmlAttr($city) ?>" name="city" id="city" title="<?= $block->escapeHtmlAttr(__('City')) ?>" placeholder="<?= $block->escapeHtml(__('City'))  ?>" class="input-text required-entry">
            </div>
        </div>
        <?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>
        <?php //phpcs:enable?>
        <div class="field street required">
            <label for="street_1" class="label"><span><?= /* @noEscape */ __('Street') ?></span></label>
            <div class="control">
                <input type="text" name="street[]"
                       value="<?= $block->escapeHtmlAttr($block->getStreetLine(1, $street)) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                       id="street_1"
                       placeholder="<?= $block->escapeHtml(__('Street Address')) ?>"
                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
            </div>
        </div>
        <div class="address-container">
            <div class="field region required">
                <label for="region_id" class="label"><span><?= /* @noEscape */ $block->escapeHtmlAttr(__('Region')) ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Region')) ?>" class="validate-select region_id" style="display:none;">
                        <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                    </select>
                    <?php //phpcs:disable?>
                    <input type="text" id="region" name="region" value="<?= $block->escapeHtmlAttr($region) ?>" title="<?= /* @noEscape */ __('Region') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>" style="display:none;">
                    <?php //phpcs:enable?>
                </div>
            </div>
        </div>
        <div class="field city">
            <label for="zip" class="label">
                <span><?= $block->escapeHtml(__('ZIP/Postal Code')) ?></span>
            </label>
            <div class="control">
                <input type="text" value="<?= $block->escapeHtmlAttr($postCode); ?>" name="zip" id="zip" title="<?= $block->escapeHtmlAttr(__('ZIP/Postal Code')) ?>"  placeholder="<?= $block->escapeHtml(__('ZIP/Postal Code')) ?>">
            </div>
        </div>
    </div>
</div>
<input type="hidden" name="address_id" value="<?= $addressId ?>">
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $countryViewModel->getRegionDisplayAll() ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                <?php //phpcs:disable?>
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                <?php //phpcs:enable?>
                "defaultRegion": "<?= (int) $regionId ?>",
                <?php //phpcs:disable?>
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
                <?php //phpcs:enable?>
            }
        }
    }
</script>
