<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Retailplace_CustomerAccount
 *
 * @copyright   Copyright (c) 2021 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author      Dmitriy Fionov <dmitriy@tradesquare.com.au>
 */

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Retailplace\CustomerAccount\Helper\ApprovalStatus $approvalStatus */
$approvalStatus = $this->helper('Retailplace\CustomerAccount\Helper\ApprovalStatus');

/** @var \Retailplace\CustomerAccount\ViewModel\FinishPage $viewModel */
$viewModel = $block->getViewModel();
?>
<div class="loading-mask" id="edit-loading-mask" data-role="loader">
    <div class="loader">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
             alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
             style="position: absolute;">
    </div>
</div>
<?= $block->getChildHtml('messages'); ?>
<div class="customer-edit" id="customer-edit">
    <div class="steps">
        <div class="step personal-info-step" id="register" style="display: none">
            <h2><?php echo __('Business details and interest'); ?></h2>
            <form class="customer-edit-form" action="#" data-mage-init='{"validation": {}}'>
                <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getCustomer())->toHtml() ?>
                <?= $block->getLayout()->createBlock(\Retailplace\CustomerAccount\Block\Widget\PhoneNumber::class)->setObject($block->getCustomer())->toHtml() ?>
                <div class="field choice">
                    <input type="checkbox" name="change_email" id="change-email" placeholder="<?= $block->escapeHtml(__('Change Email'))?>" data-role="change-email" value="1" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
                    <label class="label" for="change-email"><span><?= $block->escapeHtml(__('Change Email')) ?></span></label>
                </div>
                <div class="field choice">
                    <input type="checkbox" name="change_password" id="change-password"  placeholder="<?= $block->escapeHtml(__('Change Password'))?>"  data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()) : ?> checked="checked"<?php endif; ?> class="checkbox" />
                    <label class="label" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
                </div>
                <fieldset class="fieldset password" data-container="change-email-password">
                    <legend class="legend"><span data-title="change-email-password"><?= $block->escapeHtml(__('Change Email and Password')) ?></span></legend><br>
                    <div class="field email required" data-container="change-email">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input type="email" name="email" id="email" autocomplete="email" placeholder="<?= $block->escapeHtml(__('Email'))?>" data-input="change-email" value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
                        </div>
                    </div>
                    <div class="field password current required">
                        <label class="label" for="current-password"><span><?= $block->escapeHtml(__('Current Password')) ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="current_password" id="current-password" placeholder="<?= $block->escapeHtml(__('Current Password'))?>" data-input="current-password" autocomplete="off" />
                        </div>
                    </div>
                    <div class="field new password required" data-container="new-password">
                        <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="password" id="password"
                                   data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                                   data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                                   placeholder="<?= $block->escapeHtml(__('New Password'))?>"
                                   data-input="new-password"
                                   data-validate="{required:true, 'validate-customer-password':true}"
                                   autocomplete="off" />
                            <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                                <div id="password-strength-meter" class="password-strength-meter">
                                    <?= $block->escapeHtml(__('Password Strength')) ?>:
                                    <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field confirmation password required" data-container="confirm-password">
                        <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                                   placeholder="<?= $block->escapeHtml(__('Confirm New Password'))?>"
                                   data-input="confirm-password"
                                   autocomplete="off" />
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="step business-info-step" id="business_info" style="display: none">
            <h2><?php echo __('Business details and interest'); ?></h2>
            <form action="#" data-mage-init='{"validation": {}}'>
                <div class="business-wrap">
                    <?= $block->getLayout()->createBlock(\Retailplace\CustomerAccount\Block\Widget\BusinessName::class)->setObject($block->getCustomer())->toHtml() ?>
                    <?= $block->getLayout()->createBlock(\Retailplace\CustomerAccount\Block\Widget\Abn::class)->setObject($block->getCustomer())->toHtml() ?>
                </div>
                <?= $block->getChildHtml('address'); ?>
            </form>
        </div>
        <div class="step preferences-step" id="preferences" style="display: none">
            <form action="#" data-mage-init='{"validation": {}}'>
                <?= $block->getChildhtml('preferences_question'); ?>
            </form>
        </div>
        <div class="step finish-step" id="finish" style="display: none">
            <?php if ($approvalStatus->isIncompleteApplication()) : ?>
                <div class="approval-conditional">
                    <img src="<?php echo $block->getViewFileUrl('Retailplace_CustomerAccount::images/finish.png'); ?>"
                         alt="finish" />
                    <h2><?= __('You are conditionally approved to buy on TradeSquare!'); ?></h2>
                    <form method="post" id="upload-file-form" action="<?= $block->escapeUrl($block->getUrl('sign-up-page/account/contactInfo')) ?>" enctype="multipart/form-data"
                          data-mage-init='{"validation": {}}'>
                        <?= $block->getLayout()->createBlock(\Retailplace\CustomerAccount\Block\Widget\BusinessLink::class)->setObject($block->getCustomer())->toHtml() ?>
                        <?= $block->getLayout()->createBlock(\Retailplace\CustomerAccount\Block\Widget\UploadFile::class)->setObject($block->getCustomer())->toHtml() ?>
                        <div class="document-note">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('approval-document-note')
                                ->toHtml();
                            ?>
                        </div>
                        <span class="message-placeholder"></span>
                        <div class="action">
                            <button type="button" id="btn-done"><span><?= __('Done') ?></span></button>
                        </div>
                        <input type="hidden"
                               name="referer"
                               value="<?=$block->escapeHtml($block->getRequest()->getParam('referer'))?>" />
                    </form>
                    <script type="text/x-magento-init">
                        {
                            "#upload-file-form": {
                                "Retailplace_CustomerAccount/js/contact-info" : {}
                            }
                        }
                    </script>
                </div>
                <div class="approval-success" style="display: none">
                    <?= $block->getChildHtml('customer_account_edit_congratulation', false) ?>
                </div>
            <?php else: ?>
                    <span class="text"><?= $block->escapeHtml(__('Updated data successfully.')); ?></span>
                    <div class="action">
                        <button onclick="window.location.href='<?= $block->escapeHtmlAttr($block->escapeUrl($viewModel->getRefererUrl())) ?>'" type="button" id="btn-done"><span><?= __('Start shopping') ?></span></button>
                    </div>
            <?php endif; ?>
        </div>
        <div class="actions btn-actions" style="display: none;">
            <div class="primary">
                <a class="action next" data-value="next" id="next-step" href="#"><span><?= $block->escapeHtml(__('Next')) ?></span></a>
            </div>
            <div class="secondary">
                <a class="action back" id="back-step" data-value="back" href="#"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
            </div>
        </div>
    </div>
    <?= $block->getChildHtml('did.you.know');?>
</div>
<?= $block->getChildHtml('additional_info');?>
<script>
    window.customerData = {
        "id": <?= $block->getCustomer()->getId()?>,
        "email": "<?= $block->getCustomer()->getEmail()?>",
        "website_id": <?= $block->getCustomer()->getWebsiteId()?>
    };
    window.incompleteApplication = <?= (int) $approvalStatus->isIncompleteApplication(); ?>;
    window.autoApprovalStatus = "<?= $approvalStatus->getAutoApprovalStatus(); ?>";
    window.editUrlEncode = "<?= $this->helper('Retailplace\CustomerAccount\Helper\Url')->urlEncoder($block->getUrl('customer/account/edit'));?>";
</script>
<script>
    require([
        'mage/url',
        'Magento_Ui/js/block-loader'
    ], function(url, blockLoader) {
        blockLoader(
            "<?= $block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))) ?>"
        );
        return url.setBaseUrl('<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl())) ?>');
    })
</script>
<?php
$_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class);
?>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()) : ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else : ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Retailplace_CustomerAccount/js/process-update" : {},
            "Retailplace_CustomerAccount/js/view/address" : {}
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.customer-edit-form"
            }
        }
    }
</script>
