<?php
/**
 * @category   Retailplace
 * @package    Retailplace_Wholesalepartnerssec
 * @author     ishvarmagento@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Retailplace\Wholesalepartnerssec\Block;

use Magento\Framework\View\Element\Template\Context;
use Retailplace\Wholesalepartnerssec\Model\WholesalepartnerssecFactory;
/**
 * Wholesalepartnerssec List block
 */
class WholesalepartnerssecListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Wholesalepartnerssec
     */
    protected $_wholesalepartnerssec;
    public function __construct(
        Context $context,
        WholesalepartnerssecFactory $wholesalepartnerssec
    ) {
        $this->_wholesalepartnerssec = $wholesalepartnerssec;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Retailplace Wholesalepartnerssec Module List Page'));
        
        if ($this->getWholesalepartnerssecCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'retailplace.wholesalepartnerssec.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getWholesalepartnerssecCollection()
            );
            $this->setChild('pager', $pager);
            $this->getWholesalepartnerssecCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getWholesalepartnerssecCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $wholesalepartnerssec = $this->_wholesalepartnerssec->create();
        $collection = $wholesalepartnerssec->getCollection();
        $collection->addFieldToFilter('status','1');
        //$wholesalepartnerssec->setOrder('wholesalepartnerssec_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}