<?php
/**
 * @category   Retailplace
 * @package    Retailplace_Wholesalepartnerssec
 * @author     ishvarmagento@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Retailplace\Wholesalepartnerssec\Block;

use Magento\Framework\View\Element\Template\Context;
use Retailplace\Wholesalepartnerssec\Model\WholesalepartnerssecFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Wholesalepartnerssec View block
 */
class WholesalepartnerssecView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Wholesalepartnerssec
     */
    protected $_wholesalepartnerssec;
    public function __construct(
        Context $context,
        WholesalepartnerssecFactory $wholesalepartnerssec,
        FilterProvider $filterProvider
    ) {
        $this->_wholesalepartnerssec = $wholesalepartnerssec;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Retailplace Wholesalepartnerssec Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $wholesalepartnerssec = $this->_wholesalepartnerssec->create();
        $singleData = $wholesalepartnerssec->load($id);
        if($singleData->getWholesalepartnerssecId() || $singleData['wholesalepartnerssec_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}