<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
$wholesalePartnersSql = $connection->select()
    ->from(['rw' => $resource->getTableName('retailplace_wholesalepartnerssec')])
    ->joinLeft(["mo" => $resource->getTableName('mirakl_shop')], "mo.id = rw.title")
    ->where("mo.state = ?", "open")
    ->where("rw.status = ?", "1")
    ->limit(-1);

$wholesalePartners = $connection->fetchAll($wholesalePartnersSql);

$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
    ->getStore()
    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$priceHelper = $this->helper("\Magento\Framework\Pricing\Helper\Data");
?>
<?php if ($wholesalePartners): ?>
    <?php //echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('additional_showroom_feature_title')->toHtml(); ?>
    <!-- <h2><?php //echo __('Inspired by our wholesale partners ');?></h2> -->

<?php endif; ?>
<ul class="slider-post-seller-one">
    <?php $i = 0;
    foreach ($wholesalePartners as $wholesalePartner): ?>
        <li>
            <div class="seller_block_bg">
                <?php $selerid = $wholesalePartner['id']; ?>
                <a href="<?php echo $this->getBaseUrl() . 'marketplace/shop/view/id/' . $selerid ?>">
                    <img src="<?php echo $mediaUrl . $wholesalePartner['image']; ?>" alt="" width="300" height="200"
                         class="no-lazy"/>
                </a>
                <div class="parternt">
                    <div class="seller-name">
                        <a href="<?php echo $this->getBaseUrl() . 'marketplace/shop/view/id/' . $selerid ?>">
                            <?php echo $wholesalePartner['name']; ?>
                        </a>
                    </div>
                    <?php $minOrderAmount = $wholesalePartner['min-order-amount'] ?? ""; ?>
                    <?php if ($minOrderAmount > 0): ?>
                        <?php echo $priceHelper->currency($minOrderAmount, true, false)  . ' Minimum'; ?>
                    <?php else: ?>
                        <?php echo __('No Minimum'); ?>
                    <?php endif; ?>
                </div>
            </div>
        </li>

    <?php endforeach; ?>
</ul>
