<?php
/**
 * @category   Retailplace
 * @package    Retailplace_Wholesalepartnerssec
 * @author     ishvarmagento@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Retailplace\Wholesalepartnerssec\Controller\Index;

use Magento\Framework\App\Action\Context;
use Magento\Framework\Exception\NotFoundException;
use Retailplace\Wholesalepartnerssec\Block\WholesalepartnerssecView;

class View extends \Magento\Framework\App\Action\Action
{
	protected $_wholesalepartnerssecview;

	public function __construct(
        Context $context,
        WholesalepartnerssecView $wholesalepartnerssecview
    ) {
        $this->_wholesalepartnerssecview = $wholesalepartnerssecview;
        parent::__construct($context);
    }

	public function execute()
    {
    	if(!$this->_wholesalepartnerssecview->getSingleData()){
    		throw new NotFoundException(__('Parameter is incorrect.'));
    	}
    	
        $this->_view->loadLayout();
        $this->_view->getLayout()->initMessages();
        $this->_view->renderLayout();
    }
}
