<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

/**
 * Sm_ListingTabs
 *
 * @copyright   Copyright (c) 2021 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author      Dmitriy Fionov <dmitriy@tradesquare.com.au>
 * @author      Evgeniy Derevyanko <evgeniy@tradesquare.com.au>
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
/** @var \Retailplace\ChannelPricing\Block\ListingTabs $block */
?>
<?php
$miraklFrontendDemoHelper = $this->helper('Retailplace\MiraklFrontendDemo\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$miraklOfferTable = $resource->getTableName('mirakl_offer');
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
    ->getStore()
    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currency = $currencysymbol->getStore()->getCurrentCurrencyCode();
$currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currency);
$currencySymbol = $currency->getCurrencySymbol();
/** @var \Retailplace\CustomerAccount\Helper\ApprovalContext $approvalHelper */
$approvalHelper = $this->helper('Retailplace\CustomerAccount\Helper\ApprovalContext');
?>
<?php
if ($this->_isAjax()) {
    $products = $this->_ajaxLoad();
    $config = $this->_getConfig();
} else {
    $config = $this->getData('config');
    $products = $this->getData('products');
}
$block->setProductList($products->getItems());
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config = $this->helper('Sm\Market\Helper\Data');
$homeStyle = $_config->getThemeLayout('home_style');
$viewMode = 'grid';
$image = 'category_page_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type_loadmore = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark = $type_loadmore ? ' ltabs-mark ' : '';

$nb_type_show = $config['type_show'];

$nb_rows = 7;
$i = 0;
$count = count($products);
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
$productids = null;
if (count($products)) {
    ?>
    <div class="<?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div
            class="products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>" <?php echo $type_loadmore ? 'data-liffect="fadeIn"' : ''; ?>>
            <?php foreach ($products as $_product):
                $offer = $objectManager->create('Mirakl\FrontendDemo\Helper\Offer')->getBestOffer($_product); ?>
                <?php $productUrl = $offer ?
                $this->getUrl('seller/') . $offer->getShopId() . '/' . $_product->getUrlKey() . '.html'
                : $_product->getProductUrl(); ?>
                <?php
                if ($offer) {
                    $_product->setData('main_offer', $offer);
                }
                ?>
                <?php $productids[] = $_product->getId(); ?>
                <?php /* @escapeNotVerified */
                echo ($iterator++ == 1) ? '<div class="item product product-item ' . $cls_mark . '">' : '</div><div class="item product product-item ' . $cls_mark . '">' ?>
                <div
                    class="product-item-info <?php if (!$customerSession->isLoggedIn() || !$approvalHelper->checkIsApproval()): ?>signup_button_bg<?php endif; ?>"
                    data-container="product-<?= /* @escapeNotVerified */
                    $viewMode ?>">
                    <div class="all-label all-label-top">
                        <?php echo $this->helper('Retailplace\MiraklFrontendDemo\Helper\Data')->getCalculatedMargin($_product); ?>
                        <?php if ($_product->getData('is_businesses')): ?>
                            <div class="retail-business-label">
                                <div class="is_businesses_label">
                                    <span><?php echo __('FOR TRADE'); ?></span>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    } ?>
                    <?php // Product Image
                    ?>
                    <div class="image-grid">
                        <a href="<?= /* @escapeNotVerified */ $productUrl ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                    </div>
                    <div class="product-item-inner">
                        <div
                            class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                            <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                <?php if ($customerSession->isLoggedIn()): ?>
                                    <a class="action tocart primary"
                                       title="<?= $block->escapeHtml(__('View Details')) ?>"
                                       href="<?= /* @escapeNotVerified */ $productUrl ?>">
                                                <span><?= /* @escapeNotVerified */
                                                    __('View Details') ?></span>
                                    </a>
                                <?php endif; ?>
                                <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form"
                                          data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                          action="<?= /* @NoEscape */
                                          $postParams['action'] ?>" method="post">
                                        <input type="hidden" name="product"
                                               value="<?= /* @escapeNotVerified */
                                               $postParams['data']['product'] ?>">
                                        <input type="hidden" name="<?= /* @escapeNotVerified */
                                        Action::PARAM_NAME_URL_ENCODED ?>"
                                               value="<?= /* @escapeNotVerified */
                                               $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                        <?= $block->getBlockHtml('formkey') ?>
                                    </form>

                                <?php else: ?>
                                    <?php if ($_product->isAvailable()): ?>
                                        <div class="stock available"><span><?= /* @escapeNotVerified */
                                                __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?php
                                                //echo __('Out of stock')?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <div data-role="add-to-links"
                                 class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist <?php echo "wishlist" . $_product->getId(); ?>"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php /* @escapeNotVerified */
                                           echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist" role="button">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                <?php } ?>

                                <?php if ($_config->getAdvanced('show_compare_button')) { ?>
                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                    <a href="#" class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php /* @escapeNotVerified */
                                       echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                                <span><?php /* @escapeNotVerified */
                                                    echo __('Add to Compare') ?></span>
                                    </a>
                                <?php } ?>
                            </div>
                        </div>
                     </div>
                    <!--LABEL PRODUCT-->
                    <?php
                    $orgprice = (float) $_product->getPrice();
                    $fnPrice = (float) $_product->getFinalPrice();

                    if ($_config->getAdvanced('show_salelabel')) {
                        if ($fnPrice < $orgprice) { ?>
                            <div class="label-product label-sale">
                        <span class="sale-product-icon">
                            <?php echo __('Sale'); ?>
                        </span>
                            </div>
                        <?php }
                    } ?>
                    <?php if (!$_product->getIsSalable() && $_product->getTypeId() == 'simple'): ?>
                        <div class="out-of-stock">
                            <div class="out-off-stock-img">
                                <img src="<?php echo $mediaUrl . "wysiwyg/out_off_stock.png"; ?>" alt=""/>
                            </div>
                            <span class="lable"><?php echo __('Coming Soon'); ?></span>
                        </div>
                    <?php endif; ?>

                    <!--END LABEL PRODUCT-->
                    <div class="all-label">
                        <?php if ($offer): ?>
                            <?php
                            $price = null;
                            $origin_price = null;
                            $additional_infoclearance = '';
                            $checkclearance = $offer->getClearance();
                            $price = $offer->getPrice();
                            $origin_price = $offer->getOriginPrice(); ?>
                            <?php if (($price < $origin_price) && $checkclearance == 1): ?>
                                <div class="sale-label">
                                    <span><?php echo __('Clearance'); ?></span>
                                </div>
                            <?php elseif ($price < $origin_price): ?>
                                <div class="sale-label">
                                    <span><?php echo __('Sale'); ?></span>
                                </div>
                            <?php elseif ($checkclearance == 1): ?>
                                <div class="sale-label">
                                    <span><?php echo __('Clearance'); ?></span>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php /*if ($price < $origin_price) : ?>
                        <div class="sale-label">
                            <span>
                                <?php echo __('Sale'); ?>
                            </span>
                        </div>
                    <?php endif;?>
                    <?php if($additional_info == '{"clearance":"true"}'):?>
                        <div class="sale-label">
                            <span>
                                <?php echo __('Clearance'); ?>
                            </span>
                        </div>
                    <?php endif; */
                        ?>
                        <?php
                        $made_in_au = $_product->getData('made_in_au');
                        $designed_in_au = $_product->getData('designed_in_au'); ?>

                        <?php if ($made_in_au && $designed_in_au): ?>
                            <div class="design-by-label">
                                <span><?php echo __('Made In AU'); ?></span>
                            </div>
                        <?php elseif ($designed_in_au): ?>
                            <div class="made-by-label">
                                <span><?php echo __('Designed In AU'); ?></span>
                            </div>
                        <?php elseif ($made_in_au): ?>
                            <div class="design-by-label">
                                <span><?php echo __('Made In AU'); ?></span>
                            </div>
                        <?php endif; ?>

                        <?php if ($block->productIsAuPostExclusive($_product)): ?>
                            <div class="au-post-exclusive-label">
                                <span><?= __($block->getAuPostExclusiveLabel()); ?></span>
                            </div>
                        <?php endif; ?>

                        <?php if ($block->productIsNlnaExclusive($_product)): ?>
                            <div class="nlna-exclusive-label">
                                <span><?= __($block->getNlnaExclusiveLabel()); ?></span>
                            </div>
                        <?php endif; ?>

                        <?php if ($block->productIsOpenDuringXmas($_product)): ?>
                            <div class="open-during-xmas-label">
                                <span><?= __($block->getOpenDuringXmasLabel()); ?></span>
                            </div>
                        <?php endif; ?>

                        <?php
                        $now = date("Y-m-d");
                        $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                        $newsTo = substr($_product->getNewsToDate(), 0, 10);

                        if (($newsTo != '' || $newsFrom != '')) {
                            if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                <div class="new-label">
                                    <span><?php echo __('New'); ?></span>
                                </div>
                            <?php }
                        } ?>

                        <div class="free-shipping-label">
                            <!-- fee -->
                        </div>

                    </div>
                    <div class="product-detial-bg">
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $productUrl ?>">
                                    <?= /* @escapeNotVerified */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?php if ($_product->getIsSalable()): ?>
                                <?= /* @escapeNotVerified */
                                $block->getProductPrice($_product) ?>

                            <?php endif; ?>
                            <?php if ($offer): ?>
                                <?php

                                $minimum = null;
                                $minimum = $offer->getMinOrderQuantity();
                                if ($minimum == 0):
                                    $minimum = 1;
                                endif; ?>
                                <?= $miraklFrontendDemoHelper->getMinimumQtyHtml($_product, $minimum); ?>
                            <?php endif; ?>
                            <?= $block->getProductDetailsHtml($_product) ?>

                            <?php
                            if ((int) $config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
                                $specialToDate = $_product->getSpecialToDate(); ?>
                                <div class="deals-countdown"
                                     data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
                                    <div class="deals-time time-day">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                    <div class="deals-time time-hours">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                    <div class="deals-time time-mins">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                    <div class="deals-time time-secs">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                </div>
                                <?php
                            } ?>
                            <?php if (!$customerSession->isLoggedIn()): ?>
                                <div class="seller-info mobile-view"></div>
                            <?php endif; ?>
                            <?php
                            $visiblePromotions = $block->getVisiblePromotionsByProduct($_product);
                            $promotionsVisible = $block->isPromotionsBlockVisible($_product);
                            ?>
                            <?php if ($promotionsVisible): ?>
                                <div class="seller-promotions">
                                    <span class="promotion-block-title"><?= __('Supplier Specials') ?></span>
                                    <?php foreach ($visiblePromotions as $sellerPromotion): ?>
                                        <span class="seller-promotion">
                                        <?= $block->escapeHtml($sellerPromotion->getLocalizedPublicDescription()) ?>
                                    </span>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="product details product-item-details hover">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $productUrl ?>">
                                    <?= /* @escapeNotVerified */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>

                            <?php if ($_product->getIsSalable()): ?>
                                <?= /* @escapeNotVerified */
                                $block->getProductPrice($_product) ?>

                            <?php endif; ?>
                            <?php if ($offer): ?>
                                <?php
                                $minimum = null;
                                $minimum = $offer->getMinOrderQuantity();
                                if ($minimum == 0):
                                    $minimum = 1;
                                endif; ?>
                                <?= $miraklFrontendDemoHelper->getMinimumQtyHtml($_product, $minimum); ?>
                            <?php endif; ?>

                            <?= $block->getProductDetailsHtml($_product) ?>
                            <?php if ($promotionsVisible): ?>
                                <div class="seller-promotions">
                                    <span class="promotion-block-title"><?= __('Supplier Specials') ?></span>
                                    <?php foreach ($visiblePromotions as $sellerPromotion): ?>
                                        <span class="seller-promotion">
                                        <?= $block->escapeHtml($sellerPromotion->getLocalizedPublicDescription()) ?>
                                    </span>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                            <div class="seller-info">
                                <a href="<?= /* @escapeNotVerified */ $productUrl ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                   class="action more product-url"></a>
                                <?php if ($offer): ?>
                                    <?php

                                    $seller_info = $offer->getShopId();
                                    $miracaldata = $connection->fetchAll("SELECT * FROM mirakl_shop where id='$seller_info'"); ?>

                                    <?php if ($miracaldata && $_product->getIsSalable()): ?>
                                        <?php foreach ($miracaldata as $value): ?>
                                            <?php $_info = $value['additional_info']; ?>
                                            <div class="seller-name">
                                                <?php echo "By " . $value['name']; ?>
                                            </div>
                                            <?php
                                            $data = $this->helper(\Retailplace\Utility\Helper\Data::class)->unserialize($_info);
                                            $minOrderAmount = $value['min-order-amount']; ?>

                                            <?php if ($minOrderAmount > 0): ?>
                                                <div class="mimum-order">
                                                    <?php echo $currencySymbol . $minOrderAmount . ' Minimum'; ?>
                                                </div>
                                            <?php else: ?>
                                                <div class="mimum-order">
                                                    <?php echo __('No Minimum'); ?>
                                                </div>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo ($iterator == count($products) + 1) ? '</div>' : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
    <?php
} else {
    if (!$this->_isAjax()) { ?>
        <div class="message info empty">
            <div><?php /* @escapeNotVerified */
                echo __('We can\'t find products matching the selection.') ?></div>
        </div>
    <?php }
} ?>
