<?php 
$min=$block->getMindigits();
$max=$block->getMaxdigits();
 ?>
<style type="text/css">
    #mob
    {
        height: 36px
    }
    .intl-tel-input {
    width: 35%;
}
</style>
<fieldset class="fieldset create account">
    <legend class="legend"><span><?php echo __('Additional Information') ?></span></legend>
    <div class="field">
        <div class="control" id="mob">
            <input type="text" name="mobilenumber" id="mobilenumber" title="<?php echo __('mobilenumber') ?>" class="input-text mobilenumber" autocomplete="off" placeholder="Mobile Number" maxlength="14"  pattern="[0-9]">
        </div>
        <div class="comment"><?php echo __('Enter Number With Country code & without any sign. e.g:-(91xxxxxxx09)') ?></div>
        <?php if($block->IsSignUpConfirmation()) : ?>
        <div id="otpdiv" class="control">
            <input type="password" name="otp" id="otp" title="<?php echo __('otp') ?>" class="input-text" autocomplete="off" placeholder="OTP" maxlength="10">
        </div>
        <div id="waitsmsdiv">
            <img src='<?php echo $this->getViewFileUrl('images/loader-1.gif'); ?>' alt="Please Wait..." width="30px" height="30px">
        </div>
        <div id="otpbtndiv">
            <button id="getotpbtn" name="getotpbtn" type="button" class="<?php echo $block->getButtonclass();?>" title="Get OTP">
                <span><?php echo __('Get OTP') ?></span>
            </button>
            <button id="resendotpbtn" name="resendotpbtn" type="button" class="<?php echo $block->getButtonclass();?>" title="Resend OTP">
                <span><?php echo __('Resend OTP') ?></span>
            </button>
        </div>
        <?php endif; ?>
        <div id="smserror" name="smserror" generated="true" class="mage-error"></div>
    </div>
</fieldset>
<?php if($block->IsSignUpConfirmation()) : ?>
    <script>

        require(['jquery', 'jquery/ui'], function($)
        {
            function Smsresetdata()
            {
                $('#mobilenumber').removeClass('mage-error');
                $('#smserror').html('');
            }

            function Smstoggeldata(Elementid)
            {
                $(Elementid).toggle();
            }

            $("#getotpbtn").click(function(e)
            {
                //Reset Everything
                Smsresetdata();

                //Number Validation
                var mobile = $('#mobilenumber').val();
                if(mobile == null || mobile == '')
                {
                    $('#mobilenumber').addClass('mage-error');
                    $('#smserror').html('<?php echo __('This is a required field.') ?>');
                    return false;
                }
                if(!$.isNumeric(mobile) || mobile.substring(0,1)=='+' || mobile.substring(0,1)=='-')
                {
                    $('#mobilenumber').addClass('mage-error');
                    $('#smserror').html('<?php echo __('Please, Enter Valid Mobile Number.') ?>');
                    return false;
                }
                if(mobile.length <= <?php echo $min ?> || mobile.length >=<?php echo $max ?>)
                {
                    $('#mobilenumber').addClass('mage-error');
                    $('#smserror').html('<?php echo __('Your Mobile Number Should Be Between '.$min.' & '. $max.'.') ?>');
                    return false;
                }
                


                //Send OTP To Number
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->getUrl('smspro/customer/register')?>',
                    data:{'mobile':mobile},
                    beforeSend: function()
                    {
                        Smsresetdata();
                        Smstoggeldata('#getotpbtn');
                        Smstoggeldata('#waitsmsdiv');
                    },
                    success: function(data)
                    {
                        if(data == 'success')
                        {
                            Smstoggeldata('#waitsmsdiv');
                            Smstoggeldata('#otpdiv');
                            Smstoggeldata('#resendotpbtn');
                            $('#mobilenumber').attr('readonly', true);
                        }
                        else
                        {
                            Smstoggeldata('#waitsmsdiv');
                            Smstoggeldata('#getotpbtn');
                            $('#smserror').html(data);
                        }
                    },
                    error: function() {
                        Smstoggeldata('#waitsmsdiv');
                        Smstoggeldata('#getotpbtn');
                        $('#smserror').html('<?php echo __('Something went wrong, Try again later.') ?>');
                    }
                });
            });

            $("#resendotpbtn").click(function(e)
            {
                //Reset Everything
                Smsresetdata();

                var mobile = $('#mobilenumber').val();
                //Re-Send OTP To Number
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->getUrl('smspro/customer/register')?>',
                    data:{'mobile':mobile},
                    beforeSend: function()
                    {
                        Smsresetdata();
                        Smstoggeldata('#resendotpbtn');
                        Smstoggeldata('#waitsmsdiv');
                    },
                    success: function(data)
                    {
                        Smstoggeldata('#waitsmsdiv');
                        if(data != 'success')
                        {
                            $('#smserror').html(data);
                        }
                    },
                    error: function() {
                        Smstoggeldata('#waitsmsdiv');
                        $('#smserror').html('<?php echo __('Something went wrong, Try again later.') ?>');
                    }
                });
            });
        });
    </script>
<?php endif; ?>