<?php

/**
 * Retailplace_MiraklMcm
 *
 * @copyright Copyright © 2021 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author    Satish Gumudavelly <satish@kipanga.com.au>
 */

declare(strict_types=1);

namespace Retailplace\MiraklMcm\Console;

use Symfony\Component\Console\Command\Command;
use Retailplace\MiraklMcm\Model\BestSellerAttributeUpdater;
use Magento\Framework\App\State;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Magento\Framework\App\Area;
use Exception;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Exception\NoSuchEntityException;

/**
 * Class BestSellerProductAttributeUpdate
 */
class BestSellerProductAttributeUpdate extends Command
{
    /** @var string */
    public const COMMAND_NAME = 'retailplace:best-seller:attribute-update-values';
    /**
     * @var State
     */
    private $state;
    /**
     * @var BestSellerAttributeUpdater
     */
    private $bestSellerAttributeUpdater;

    /**
     * BestSellerProductAttributeUpdate constructor.
     * @param State $state
     * @param BestSellerAttributeUpdater $bestSellerAttributeUpdater
     * @param null $name
     */
    public function __construct(
        State $state,
        BestSellerAttributeUpdater $bestSellerAttributeUpdater,
        $name = null
    ) {
        $this->state = $state;
        $this->bestSellerAttributeUpdater = $bestSellerAttributeUpdater;
        parent::__construct($name);
    }

    /**
     * Configure CLI Command
     */
    protected function configure()
    {
        $this->setName(self::COMMAND_NAME);
        $this->setDescription('Update best seller attribute from top_product to best_seller attribute');
        $this->setHelp(
            <<<HELP
It will get all top_product product attribute values where its option
will match with label Best seller and add flag 1 for same product for
best_seller product attribute.

HELP
        );
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return void
     * @throws LocalizedException
     * @throws NoSuchEntityException
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->processArea();
        $output->writeln(__('<info>Updating Best seller attribute values...</info>'));
        $count = $this->bestSellerAttributeUpdater->updateBestSellerValues();
        $output->writeln(__('<info>%1 Best seller attribute values were updated.</info>', $count));
    }

    /**
     * Set Area Code for CLI
     *
     * @throws LocalizedException
     */
    protected function processArea()
    {
        try {
            $this->state->getAreaCode();
        } catch (Exception $e) {
            $this->state->setAreaCode(Area::AREA_FRONTEND);
        }
    }
}
