<?php
/**
 * Retailplace_Insider
 *
 * @copyright   Copyright © 2022 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author      Evgeniy Derevyanko <evgeniy@tradesquare.com.au>
 */

use Magento\Framework\App\Action\Action;

/** @var \Retailplace\Recentview\Block\ListingTabsRecentlyViewed $block */
$tag_id = $this->_tagId();
$cmsBlock = $this->_getConfig('cmsblock');
$mediaUrl = $block->getMediaUrl();
$currencySymbol = $block->getCurrencySymbol();
if ($this->_isAjax()) {
    $products = $this->_ajaxLoad();
    $config = $this->_getConfig();
} else {
    $config = $this->getData('config');
    $products = $this->getData('products');
}
$block->setProductList($products);
$viewMode = 'grid';
$image = 'category_page_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

$nb_rows = 7;
$i = 0;
$count = count($products);
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
$productIds = [];

if ($products && count($products)):
    ?>
    <div id="<?php echo $tag_id; ?>"
         class="sm-listing-tabs ltabs-loading-first <?php echo $this->_getConfig('type_show') . 'type'; ?>">
        <div class="ltabs-loading-css">
            <div class="loading-content">
            </div>
        </div>
        <div class="title-home-page">
            <span><?php echo __($this->_getConfig('title', 'Tab Listing')); ?></span>
        </div>
        <div class="ltabs-wrap">
            <div class="ltabs-items-container ">
                <div class="ltabs-items ltabs-items-selected ltabs-items-loaded">
                    <div class="ltabs-items-inner">
                        <?php if (!empty($products)):
                            $this->setData('products', $products);
                            $this->setData('config', $this->_getConfig());
                            ?>
                            <div class="<?php /* @escapeNotVerified */
                            echo $viewMode; ?> products-<?php /* @escapeNotVerified */
                            echo $viewMode; ?>">
                                <?php $iterator = 1; ?>
                                <div class="ins-preview-wrapper-1">
                                    <ul class="products list items product-items  owl-carousel" data-recommended-items='<?= $block->jsonSerialize($block->getData('products_sku')) ?>'>
                                        <?php foreach ($products as $_product):
                                            /** @var \Mirakl\Connector\Model\Offer $offer */
                                            $offer = $block->getBestOffer($_product); ?>
                                            <?php $productUrl = !empty($offer) ?
                                            $this->getUrl('seller/') . $offer->getShopId() . '/' . $_product->getUrlKey() . '.html'
                                            : $_product->getProductUrl(); ?>
                                            <?php $productIds[] = $_product->getId(); ?>
                                            <?php /* @escapeNotVerified */
                                            echo ($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                                            <li>
                                                <div
                                                    class="product-item-info <?php if (!$block->isLoggedIn() || !$block->checkIsApproval()): ?>signup_button_bg<?php endif; ?>"
                                                    data-container="product-<?= /* @escapeNotVerified */
                                                    $viewMode ?>">
                                                    <div class="all-label all-label-top">
                                                        <?php echo $this->helper('Retailplace\MiraklFrontendDemo\Helper\Data')->getCalculatedMargin($_product); ?>
                                                    </div>

                                                    <?php
                                                    $productImage = $block->getImage($_product, $image);
                                                    if ($pos != null) {
                                                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                                    } ?>
                                                    <div class="image-grid">
                                                        <a href="<?= /* @escapeNotVerified */
                                                        $productUrl ?>" class="product photo product-item-photo ins-product-box ins-element-link" event-collection="true" tabindex="-1">
                                                            <?= $productImage->toHtml() ?>
                                                        </a>
                                                    </div>
                                                    <div class="product-item-inner">
                                                        <div
                                                            class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                                            <div
                                                                class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                                                <?php if ($block->isLoggedIn()): ?>
                                                                    <a class="action tocart primary"
                                                                       title="<?= $block->escapeHtml(__('View Details')) ?>"
                                                                       href="<?= /* @escapeNotVerified */
                                                                       $productUrl ?>">
                                                <span><?= /* @escapeNotVerified */
                                                    __('View Details') ?></span>
                                                                    </a>
                                                                <?php endif; ?>
                                                                <?php if ($_product->isSaleable()): ?>
                                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                                    <form data-role="tocart-form"
                                                                          data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                                          action="<?= /* @NoEscape */
                                                                          $postParams['action'] ?>" method="post">
                                                                        <input type="hidden" name="product"
                                                                               value="<?= /* @escapeNotVerified */
                                                                               $postParams['data']['product'] ?>">
                                                                        <input type="hidden" name="<?= /* @escapeNotVerified */
                                                                        Action::PARAM_NAME_URL_ENCODED ?>"
                                                                               value="<?= /* @escapeNotVerified */
                                                                               $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                        <?= $block->getBlockHtml('formkey') ?>
                                                                    </form>

                                                                <?php else: ?>
                                                                    <?php if ($_product->isAvailable()): ?>
                                                                        <div
                                                                            class="stock available"><span><?= /* @escapeNotVerified */
                                                                                __('In stock') ?></span></div>
                                                                    <?php else: ?>
                                                                        <div class="stock unavailable"><span><?php
                                                                                //echo __('Out of stock')?></span></div>
                                                                    <?php endif; ?>
                                                                <?php endif; ?>
                                                            </div>
                                                            <div data-role="add-to-links"
                                                                 class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                                                <?php if ($block->getAdvanced('show_wishlist_button')): ?>
                                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                                        <a href="#"
                                                                           class="action towishlist <?php echo "wishlist" . $_product->getId(); ?>
                                           <?php if (in_array($_product->getId(), $block->getWislistItemIds())): ?> allready-adedd-whilist <?php endif; ?>
                                            "
                                                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                                           data-post='<?php /* @escapeNotVerified */
                                                                           echo $block->getAddToWishlistParams($_product); ?>'
                                                                           data-action="add-to-wishlist" role="button">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Add to Wish List') ?></span>
                                                                        </a>
                                                                    <?php endif; ?>
                                                                <?php endif; ?>

                                                                <?php if ($block->getAdvanced('show_compare_button')): ?>
                                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                                    <a href="#" class="action tocompare"
                                                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                                       data-post='<?php /* @escapeNotVerified */
                                                                       echo $compareHelper->getPostDataParams($_product); ?>'
                                                                       role="button">
                                                <span><?php /* @escapeNotVerified */
                                                    echo __('Add to Compare') ?></span>
                                                                    </a>
                                                                <?php endif; ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--LABEL PRODUCT-->
                                                    <?php
                                                    $orgprice = (float) $_product->getPrice();
                                                    $fnPrice = (float) $_product->getFinalPrice();

                                                    if ($block->getAdvanced('show_salelabel')):
                                                        if ($fnPrice < $orgprice): ?>
                                                            <div class="label-product label-sale">
                                                        <span class="sale-product-icon">
                                                            <?php echo __('Sale'); ?>
                                                        </span>
                                                            </div>
                                                        <?php endif;
                                                    endif; ?>
                                                    <?php if (!$_product->getIsSalable() && $_product->getTypeId() == 'simple'): ?>
                                                        <div class="out-of-stock">
                                                            <div class="out-off-stock-img">
                                                                <img
                                                                    src="<?php echo $mediaUrl . "wysiwyg/out_off_stock.png"; ?>"
                                                                    alt=""/>
                                                            </div>
                                                            <span class="lable"><?php echo __('Coming Soon'); ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                    <!--END LABEL PRODUCT-->
                                                    <div class="all-label">
                                                        <?php if ($offer): ?>
                                                            <?php
                                                            $price = null;
                                                            $origin_price = null;
                                                            $additional_infoclearance = '';
                                                            $checkclearance = $offer->getClearance();
                                                            $price = $offer->getPrice();
                                                            $origin_price = $offer->getOriginPrice(); ?>
                                                            <?php if (($price < $origin_price) && $checkclearance == 1): ?>
                                                                <div class="sale-label">
                                                                    <span><?php echo __('Clearance'); ?></span>
                                                                </div>
                                                            <?php elseif ($price < $origin_price): ?>
                                                                <div class="sale-label">
                                                                    <span><?php echo __('Sale'); ?></span>
                                                                </div>
                                                            <?php elseif ($checkclearance == 1): ?>
                                                                <div class="sale-label">
                                                                    <span><?php echo __('Clearance'); ?></span>
                                                                </div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                        <?php
                                                        $made_in_au = $_product->getData('made_in_au');
                                                        $designed_in_au = $_product->getData('designed_in_au'); ?>

                                                        <?php if ($made_in_au && $designed_in_au): ?>
                                                            <div class="design-by-label">
                                                                <span><?php echo __('Made In AU'); ?></span>
                                                            </div>
                                                        <?php elseif ($designed_in_au): ?>
                                                            <div class="made-by-label">
                                                                <span><?php echo __('Designed In AU'); ?></span>
                                                            </div>
                                                        <?php elseif ($made_in_au): ?>
                                                            <div class="design-by-label">
                                                                <span><?php echo __('Made In AU'); ?></span>
                                                            </div>
                                                        <?php endif; ?>

                                                        <?php
                                                        $now = date("Y-m-d");
                                                        $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                                                        $newsTo = substr($_product->getNewsToDate(), 0, 10);

                                                        if (($newsTo != '' || $newsFrom != '')):
                                                            if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                                                <div class="new-label">
                                                                    <span><?php echo __('New'); ?></span>
                                                                </div>
                                                            <?php }
                                                        endif; ?>
                                                        <?php if ($block->productIsAuPostExclusive($_product)): ?>
                                                            <div class="au-post-exclusive-label">
                                                                <span><?= __($block->getAuPostExclusiveLabel()); ?></span>
                                                            </div>
                                                        <?php endif; ?>

                                                        <?php if ($block->productIsNlnaExclusive($_product)): ?>
                                                            <div class="nlna-exclusive-label">
                                                                <span><?= __($block->getNlnaExclusiveLabel()); ?></span>
                                                            </div>
                                                        <?php endif; ?>

                                                        <?php if ($block->productIsOpenDuringXmas($_product)): ?>
                                                            <div class="open-during-xmas-label">
                                                                <span><?= __($block->getOpenDuringXmasLabel()); ?></span>
                                                            </div>
                                                        <?php endif; ?>

                                                        <?php if ($block->productShopIsClosed($_product)): ?>
                                                            <div class="closed-to-label">
                                                                <span><?= __($block->getClosedShopLabel($_product)); ?></span>
                                                            </div>
                                                        <?php endif; ?>

                                                        <div class="free-shipping-label">
                                                            <!-- fee -->
                                                        </div>
                                                    </div>
                                                    <div class="product-detial-bg">
                                                        <div class="product details product-item-details">
                                                            <?php
                                                            $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                                            <strong class="product name product-item-name">
                                                                <a class="product-item-link"
                                                                   href="<?= /* @escapeNotVerified */
                                                                   $productUrl ?>">
                                                                    <?= /* @escapeNotVerified */
                                                                    $block->productAttribute($_product, $_product->getName(), 'name') ?>
                                                                </a>
                                                            </strong>
                                                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                                            <?php if ($_product->getIsSalable()): ?>
                                                                <?= /* @escapeNotVerified */
                                                                $block->getProductPrice($_product) ?>

                                                            <?php endif; ?>
                                                            <?php if ($offer): ?>
                                                                <?php

                                                                $minimum = null;
                                                                $minimum = $offer->getMinOrderQuantity();
                                                                if ($minimum == 0):
                                                                    $minimum = 1;
                                                                endif; ?>
                                                                <?= $block->getMinimumQtyHtml($_product, $minimum); ?>
                                                            <?php endif; ?>
                                                            <?= $block->getProductDetailsHtml($_product) ?>

                                                            <?php
                                                            if ((int) $config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
                                                                $specialToDate = $_product->getSpecialToDate(); ?>
                                                                <div class="deals-countdown"
                                                                     data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
                                                                    <div class="deals-time time-day">
                                                                        <div class="num-time"></div>
                                                                        <div class="title-time"></div>
                                                                    </div>
                                                                    <div class="deals-time time-hours">
                                                                        <div class="num-time"></div>
                                                                        <div class="title-time"></div>
                                                                    </div>
                                                                    <div class="deals-time time-mins">
                                                                        <div class="num-time"></div>
                                                                        <div class="title-time"></div>
                                                                    </div>
                                                                    <div class="deals-time time-secs">
                                                                        <div class="num-time"></div>
                                                                        <div class="title-time"></div>
                                                                    </div>
                                                                </div>
                                                                <?php
                                                            } ?>
                                                            <?php if (!$block->isLoggedIn()): ?>
                                                                <div class="seller-info mobile-view"></div>
                                                            <?php endif; ?>
                                                            <?php
                                                            $visiblePromotions = $block->getVisiblePromotionsByProduct($_product);
                                                            $promotionsVisible = $block->isPromotionsBlockVisible($_product);
                                                            ?>
                                                            <?php if ($promotionsVisible): ?>
                                                                <div class="seller-promotions">
                                                            <span
                                                                class="promotion-block-title"><?= __('Supplier Specials') ?></span>
                                                                    <?php foreach ($visiblePromotions as $sellerPromotion): ?>
                                                                        <span class="seller-promotion">
                                                                    <?= $block->escapeHtml($sellerPromotion->getLocalizedPublicDescription()) ?>
                                                                </span>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                            <?php endif; ?>
                                                        </div>
                                                        <div class="product details product-item-details hover">
                                                            <?php
                                                            $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                                            <strong class="product name product-item-name">
                                                                <a class="product-item-link"
                                                                   href="<?= /* @escapeNotVerified */
                                                                   $productUrl ?>">
                                                                    <?= /* @escapeNotVerified */
                                                                    $block->productAttribute($_product, $_product->getName(), 'name') ?>
                                                                </a>
                                                            </strong>

                                                            <?php if ($_product->getIsSalable()): ?>
                                                                <?= /* @escapeNotVerified */
                                                                $block->getProductPrice($_product) ?>

                                                            <?php endif; ?>
                                                            <?php if ($offer): ?>
                                                                <?php
                                                                $minimum = null;
                                                                $minimum = $offer->getMinOrderQuantity();
                                                                if ($minimum == 0):
                                                                    $minimum = 1;
                                                                endif; ?>
                                                                <?= $block->getMinimumQtyHtml($_product, $minimum); ?>
                                                            <?php endif; ?>

                                                            <?= $block->getProductDetailsHtml($_product) ?>
                                                            <?php if ($promotionsVisible): ?>
                                                                <div class="seller-promotions">
                                                            <span
                                                                class="promotion-block-title"><?= __('Supplier Specials') ?></span>
                                                                    <?php foreach ($visiblePromotions as $sellerPromotion): ?>
                                                                        <span class="seller-promotion">
                                                                    <?= $block->escapeHtml($sellerPromotion->getLocalizedPublicDescription()) ?>
                                                                </span>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                            <?php endif; ?>
                                                            <div class="seller-info">
                                                                <a href="<?= /* @escapeNotVerified */
                                                                $productUrl ?>" title="<?= /* @escapeNotVerified */
                                                                $_productNameStripped ?>"
                                                                   class="action more product-url"></a>
                                                                <?php if ($offer): ?>
                                                                    <?php
                                                                    $shop = $offer->getShop();
                                                                    if ($shop->getId() && $_product->getIsSalable()): ?>
                                                                        <?php $_info = $shop->getAdditionalInfo() ?>
                                                                        <div class="seller-name">
                                                                            <?php echo "By " . $shop->getName(); ?>
                                                                        </div>
                                                                        <?php
                                                                        $data = $this->helper(\Retailplace\Utility\Helper\Data::class)->unserialize($_info);
                                                                        $minOrderAmount = $shop->getData('min-order-amount');
                                                                        ?>
                                                                        <?php if ($minOrderAmount > 0): ?>
                                                                            <div class="mimum-order">
                                                                                <?php echo $currencySymbol . $minOrderAmount . ' Minimum'; ?>
                                                                            </div>
                                                                        <?php else: ?>
                                                                            <div class="mimum-order">
                                                                                <?php echo __('No Minimum'); ?>
                                                                            </div>
                                                                        <?php endif; ?>
                                                                    <?php endif; ?>
                                                                <?php endif; ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                            <?php echo ($iterator == count($products) + 1) ? '</div>' : '' ?>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            </div>
                        <?php
                        else:
                            ?>
                            <div class="ltabs-loading">
                                <div class="loading-content">

                                </div>
                            </div>
                        <?php
                        endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->getLayout()->createBlock("Sm\ListingTabs\Block\ListingTabs")->setData(['tagid' => $this->_tagId(), 'config' => $this->_getConfig()])->setTemplate("Sm_ListingTabs::default_js.phtml")->toHtml(); ?>
<?php
endif; ?>
<script type="text/x-magento-init">
    {
        ".sm-listing-tabs": {
            "Retailplace_Wishlist/js/ajax-wishlist" : {}
        }
    }
</script>



