<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
$GTM_code = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('gtm_code/gtm_code/gtm_code',$storeScope);
$checgtmstatus = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('gtm_code/gtm_code/enabled',$storeScope);
?>
<?php if($checgtmstatus):?>
	<!-- Google Tag Manager -->
	<script type="text/javascript" data-template="bundle-option">
	(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','<?php echo $GTM_code;?>');</script>
	<!-- End Google Tag Manager -->
<?php endif;?>
