<?php
/**
 * Recent Order Notification
 * @author      Trinh Doan
 * @copyright   Copyright (c) 2017 Trinh Doan
 * @package     TD_SoldNotification
 */
/* @var TD\SoldNotification\Block\Recentorder $block */

if (!$block->getActive()) {
    return;
}
?>
<script type="text/javascript">
    require(['jquery', 'mage/cookies', 'sold_notification'], function ($, sold_notification) {
        jQuery(document).ready(function (e) {
            var flag = 1;
            var orderId = 0;
            var totalnumber = 0;
            var cookinumber = 1;
            var date = new Date();
            var minutes = 480;
            date.setTime(date.getTime() + (minutes * 60 * 1000));

            function showNotify() {

                var cookieVal = $.cookie('shownotification');
                if (cookieVal == null) {
                    cookieVal = 0;
                }
                if (cookieVal < 2) {
                    if (flag == 1 && totalnumber < 2) {
                        jQuery.ajax({
                            url: "<?php echo $block->getUrl('soldnotification/index/'); ?>",
                            type: 'GET',
                            data: {orderId: orderId},
                            success: function (data) {
                                totalnumber = totalnumber + 1;
                                if (data['message'] != undefined) {
                                    $.notify({
                                        // options
                                        icon: '',
                                        title: '',
                                        message: data['message'],
                                        url: '',
                                        target: '_blank'
                                    }, {
                                        // settings
                                        element: 'body',
                                        position: null,
                                        type: "info",
                                        allow_dismiss: true,
                                        newest_on_top: false,
                                        showProgressbar: false,
                                        placement: {
                                            <?php echo $block->getPosition()?>
                                        },
                                        offset: 20,
                                        spacing: 10,
                                        z_index: 1031,
                                        delay: <?php echo $block->getTimeDisplay()?>,
                                        timer: 1000,
                                        url_target: '_blank',
                                        mouse_over: null,
                                        animate: {
                                            <?php echo $block->getEffect()?>
                                        },
                                        onShow: null,
                                        onShown: null,
                                        onClose: null,
                                        onClosed: null,
                                        icon_type: 'class',
                                        template: '<div data-notify="container" id=sold_notification>' +
                                            '<div class="notify-message"><img src="' + data['img'] + '"><p>' + data['message'] + '</p></div>' +
                                            '<span id="notify-close"></span>' +
                                            '</div>',
                                        disableMobile: <?php echo $block->getDisableMobile()?>,
                                        maxWidth: <?php echo $block->getMaxWidth()?>,
                                    });
                                    jQuery("#notify-close").click(function (e) {
                                        flag = 0;
                                        jQuery("#sold_notification").css('display', 'none');
                                    });
                                    cookinumber = parseInt(cookieVal) + 1;
                                    $.cookie('shownotification', cookinumber, {expires: date, path: '/'});
                                }
                            },
                            error: function () {
                                console.log('notify error');
                            }
                        });
                    }
                }
            }

            setInterval(showNotify, <?php echo $block->getTimeDelay()?>);
        });
    });
</script>
<style id="sold-notification-inline-css" type="text/css">

    #sold_notification {
        background-color: <?php echo $block->getBackgroundColor()?>;
        color: <?php echo $block->getTextColor()?> !important;
        border-radius: 6px;
    }
    #sold_notification img {
        border-radius: 6px 0 0 6px;
    }
    #sold_notification a {
        color: <?php echo $block->getHighlightColor()?> !important;
    }

    <?php echo $block->getCustomCss()?>
</style>
