<?php

/**
 * Mirakl_FrontendDemo
 *
 * @copyright   Copyright (c) 2022 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author      Dmitriy Fionov <dmitriy@tradesquare.com.au>
 * @author      Ruslan Mukhatov <ruslan@tradesquare.com.au>
 * @author      Alexander Korsun <aleksandr@tradesquare.com.au>
 * @author      Natalia Sekulich <natalia@tradesquare.com.au>
 */

/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** @var \Magento\Catalog\Model\Product $saleableItem */

use Retailplace\MiraklConnector\Rewrite\Helper\Offer as OfferHelper;

$saleableItem = $block->getSaleableItem();
$product = $saleableItem;

if (is_callable(array($saleableItem, 'getProduct'))) {
    if ($saleableItem->getProduct()) {
        $product = $saleableItem->getProduct();
    }
}

$productId = $saleableItem->getId();
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view');
$showPriceRange = !$schema;

/** @var \Magento\Framework\Pricing\Helper\Data $pricingHelper */
$pricingHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
/** @var \Magento\Catalog\Pricing\Price\RegularPrice $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Catalog\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$mainOffer = $product->getData('main_offer');
$worstOffer = $product->getData('worst_offer');

$minShippingPrice = $mainOffer ? $mainOffer->getMinShippingPrice() : 0;

/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $this->helper('Magento\Tax\Helper\Data');

/** @var \Mirakl\FrontendDemo\Helper\Tax $miraklTaxHelper */
$miraklTaxHelper = $this->helper('Mirakl\FrontendDemo\Helper\Tax');

/** @var \Mirakl\Connector\Helper\Config $config */
$config = $this->helper('Mirakl\Connector\Helper\Config');

/** @var \Mirakl\FrontendDemo\Helper\Offer $offerHelper */
$offerHelper = $this->helper('Mirakl\FrontendDemo\Helper\Offer');
if (!$mainOffer) {
    $mainOffer = $offerHelper->getBestOffer($product);
}

if ($config->getShippingPricesIncludeTax()) {
    $minShippingPriceInclTax = $minShippingPrice;
    $minShippingPriceExclTax = $miraklTaxHelper->getShippingPriceExclTax($minShippingPrice);
} else {
    $minShippingPriceInclTax = $miraklTaxHelper->getShippingPriceInclTax($minShippingPrice);
    $minShippingPriceExclTax = $minShippingPrice;
}

$oneofferPrice = $mainOffer ? $mainOffer->getPrice() : "0.00";
$oneofferOriginPrice = $mainOffer ? $mainOffer->getOriginPrice() : "0.00";
$maxPrice = $oneofferPrice;
$maxOriginPrice = $oneofferOriginPrice;
$isConfigurableProduct = $offerHelper->isConfigurableProduct($saleableItem);

$unit_type = $product->getAttributeText('unit_type');
$numberOfUnitPerPack = $product->getData('number_of_unit_per_pack');
if (!$numberOfUnitPerPack) {
    $numberOfUnitPerPack = $product->getResource()->getAttributeRawValue($product->getId(), 'number_of_unit_per_pack', 1);
}
$hasSpecialPrice = $maxPrice != $maxOriginPrice;
?>
<?php if ($hasSpecialPrice): ?>
    <?php if (!$mainOffer || $offerHelper->isOperatorProductAvailable($saleableItem)): ?>
        <?php if ($oneofferPrice): ?>
            <?php if ($unit_type == 'Package'): ?>
                <?php if ($numberOfUnitPerPack): ?>
                    <span class="packof"><?php echo __('Pack of ') . $numberOfUnitPerPack; ?></span>
                <?php endif; ?>
            <?php endif; ?>
            <div class="offer-price price-container">
                <span class="price-wrapper price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax')); ?>">
                    <span id="product-price-<?php echo $productId; ?>" data-price-amount="<?php echo $oneofferPrice; ?>" data-price-type="finalPrice" class="price-wrapper">
                        <span class="price" itemprop="price"><?php echo $formattedPrice = $pricingHelper->currency($oneofferPrice, true, false); ?></span>
                    </span>
                </span>
            </div>
            <?php if ($showPriceRange && $maxPrice > $oneofferPrice): ?>
                <div class="offer-price price-container">
                    <span class="price-wrapper price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax')); ?>">
                        <span id="product-max-price-<?php echo $productId; ?>" data-price-amount="<?php echo $maxPrice; ?>" data-price-type="finalPrice" class="price-wrapper">
                            <span class="price" itemprop="price"><?php echo $formattedPrice = $pricingHelper->currency($maxPrice, true, false); ?></span>
                        </span>
                    </span>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <?= $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema'            => $schema
            ]); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php echo $block->getLayout()->createBlock(\Mirakl\FrontendDemo\Block\Product\Offer\Price::class)
            ->setProduct($product)
            ->setOffer($mainOffer)
            ->setDisplayShippingPrice(false)
            ->setZone($block->getZone())
            ->toHtml();
        ?>
        <?php if ($showPriceRange && $worstOffer && $mainOffer->getPrice() < $worstOffer->getPrice()): ?>
            <?php echo $block->getLayout()->createBlock(\Mirakl\FrontendDemo\Block\Product\Offer\Price::class)
                ->setProduct($product)
                ->setOffer($worstOffer)
                ->setDisplayShippingPrice(false)
                ->setZone($block->getZone())
                ->toHtml();
            ?>
        <?php endif ?>
    <?php endif ?>
    <span class="offer-wrapper" style="display: <?php echo $minShippingPrice > 0 ? 'block' : 'none' ?>;">
        <?php if ($taxHelper->displayShippingBothPrices()): ?>
            <div class="offer-min-shipping-price">+ <span class="offer-min-shipping-price-amount"><?php echo $pricingHelper->currency($minShippingPriceInclTax, true, false) ?></span>&nbsp;<?php echo __('shipping') ?> <span class="offer-min-shipping-price-amount-excl-tax"><?php echo __('(Excl. Tax: %1)', $pricingHelper->currency($minShippingPriceExclTax, true, false)) ?></span></div>
        <?php elseif ($taxHelper->displayShippingPriceExcludingTax()): ?>
            <div class="offer-min-shipping-price">+ <span class="offer-min-shipping-price-amount-excl-tax"><?php echo $pricingHelper->currency($minShippingPriceExclTax, true, false) ?></span>&nbsp;<?php echo __('shipping') ?></div>
        <?php elseif ($taxHelper->displayShippingPriceIncludingTax()): ?>
            <div class="offer-min-shipping-price">+ <span class="offer-min-shipping-price-amount"><?php echo $pricingHelper->currency($minShippingPriceInclTax, true, false) ?></span>&nbsp;<?php echo __('shipping') ?></div>
        <?php endif ?>
    </span>
    <div class="regular-price-twice">
        <span class="old-price">
            <?= $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
    </div>

<?php else: ?>
    <?php if (!$mainOffer || $offerHelper->isOperatorProductAvailable($saleableItem)): ?>
        <?php if ($oneofferPrice): ?>
            <?php if ($unit_type == 'Package'): ?>
                <?php if ($numberOfUnitPerPack): ?>
                    <span class="packof"><?php echo __('Pack of ') . $numberOfUnitPerPack; ?></span>
                <?php endif; ?>
            <?php endif; ?>
            <?php if ($mainOffer): ?>
                <div class="offer-price price-container">
                    <span class="price-wrapper price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax')); ?>">
                        <span class="price" itemprop="price"><?php echo $pricingHelper->currency($oneofferPrice, true, false); ?></span>
                        <?php if ($unit_type == 'Package'): ?>
                            <?php if ($numberOfUnitPerPack): ?>
                                <span class="item"><?php echo __('/item'); ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($oneofferPrice != $oneofferOriginPrice): ?>
                            <span class="offer-old-price">
                               <span class="price" itemprop="price"><?php echo $pricingHelper->currency($oneofferOriginPrice, true, false); ?></span>
                           </span>
                        <?php endif; ?>
                    </span>
                </div>
            <?php endif; ?>
            <?php if ($showPriceRange && $maxPrice > $oneofferPrice): ?>
                <div class="offer-price price-container">
                    <span class="price-wrapper price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax')); ?>">
                        <span class="price" itemprop="price"><?php echo $pricingHelper->currency($maxPrice, true, false); ?></span>
                        <?php if ($unit_type == 'Package'): ?>
                            <?php if ($numberOfUnitPerPack): ?>
                                <span class="item"><?php echo __('/item'); ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($maxPrice != $maxOriginPrice): ?>
                            <span class="offer-old-price">
                                    <span class="price" itemprop="price"><?php echo $pricingHelper->currency($maxOriginPrice, true, false); ?></span>
                                </span>
                        <?php endif; ?>
                    </span>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <?= $block->renderAmount($finalPriceModel->getAmount(), [
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema'            => $schema
            ]); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php echo $block->getLayout()->createBlock(\Mirakl\FrontendDemo\Block\Product\Offer\Price::class)
            ->setProduct($product)
            ->setOffer($mainOffer)
            ->setDisplayShippingPrice(false)
            ->setZone($block->getZone())
            ->toHtml();
        ?>
        <?php if ($showPriceRange && $worstOffer && $mainOffer->getPrice() < $worstOffer->getPrice()): ?>
            <?php echo $block->getLayout()->createBlock(\Mirakl\FrontendDemo\Block\Product\Offer\Price::class)
                ->setProduct($product)
                ->setOffer($worstOffer)
                ->setDisplayShippingPrice(false)
                ->setZone($block->getZone())
                ->toHtml();
            ?>
        <?php endif ?>
    <?php endif ?>

    <span class="offer-wrapper" style="display: <?php echo $minShippingPrice > 0 ? 'block' : 'none' ?>;">
        <?php if ($taxHelper->displayShippingBothPrices()): ?>
            <div class="offer-min-shipping-price">+ <span class="offer-min-shipping-price-amount"><?php echo $pricingHelper->currency($minShippingPriceInclTax, true, false) ?></span>&nbsp;<?php echo __('shipping') ?> <span class="offer-min-shipping-price-amount-excl-tax"><?php echo __('(Excl. Tax: %1)', $pricingHelper->currency($minShippingPriceExclTax, true, false)) ?></span></div>
        <?php elseif ($taxHelper->displayShippingPriceExcludingTax()): ?>
            <div class="offer-min-shipping-price">+ <span class="offer-min-shipping-price-amount-excl-tax"><?php echo $pricingHelper->currency($minShippingPriceExclTax, true, false) ?></span>&nbsp;<?php echo __('shipping') ?></div>
        <?php elseif ($taxHelper->displayShippingPriceIncludingTax()): ?>
            <div class="offer-min-shipping-price">+ <span class="offer-min-shipping-price-amount"><?php echo $pricingHelper->currency($minShippingPriceInclTax, true, false) ?></span>&nbsp;<?php echo __('shipping') ?></div>
        <?php endif ?>
    </span>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()): ?>
        <a href="<?= $saleableItem->getProductUrl(); ?>" class="minimal-price-link">
            <?= $block->renderAmountMinimal(); ?>
        </a>
    <?php else: ?>
        <span class="minimal-price-link">
            <?= $block->renderAmountMinimal(); ?>
        </span>
    <?php endif; ?>
<?php endif; ?>

<div class="offer-price-description" <?php if (!$mainOffer): ?>style="display: none;"<?php endif ?>>
    <?php echo $mainOffer ? $mainOffer->getPriceAdditionalInfo() : '' ?>
</div>
<!-- start retail price -->
<?php
$retailPrice = $product->getData('retail_price');
if ($mainOffer && $offerProduct = $mainOffer->getData(OfferHelper::OFFER_PRODUCT)) {
    $retailPrice = $offerProduct->getData('retail_price');
}
?>
<?php if ($retailPrice): ?>
    <?php
    $salesItemId = (int) $saleableItem->getId();
    $retailPrice = $isConfigurableProduct ? $offerHelper->getMinRetailPrice($salesItemId) : $retailPrice;
    $maxRrp = $offerHelper->getMaxRetailPrice($salesItemId);
    ?>
    <?php if (is_numeric($retailPrice)): ?>
        <div class="retail-price">
            <span class="retail-price-text"><?php echo __("RRP "); ?></span>
            <span class="retail-price">
                <?= $pricingHelper->currency($retailPrice, true, false) ?>
                <?php if ($maxRrp > $retailPrice): ?>
                    - <?= $pricingHelper->currency($maxRrp, true, false) ?>
                <?php endif; ?>
            </span>
        </div>
    <?php endif; ?>
<?php endif; ?>
<!-- end retail price -->
<?php if (!$block->isProductList() && ($mainOffer || $retailPrice)) : ?>
    <span class="gst_inc">
<?= __("(Inc. GST)");?>
</span>

<?php endif; ?>
