<?php
/** @var $block \Magento\Framework\View\Element\Template */
?>
<div class="did-you-know" id="did-you-know">
    <div class="icon">
        <img src='<?php echo $block->getViewFileUrl('Retailplace_CustomerAccount::images/info.png'); ?>' alt="icon">
    </div>
    <div class="you-know-wrap">
        <div class="you-know-content">
            <h2><?php echo __('Did you know?'); ?></h2>
            <div class="message">
                <span class="register"><?php echo __('Shop over 100,000+ products from 400+ Australian Wholesalers. One login - it\'s that simple.'); ?></span>
            </div>
        </div>
    </div>
</div>
