<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper   = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$value         = 0;
$priceEmpty    = $priceHelper->currency($value, true, false);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
/*$customerContext = $objectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $customerContext->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);*/
$isLoggedIn = $customerSession->isLoggedIn() ? 1 : 0;
?>

<div data-block="minicart" class="minicart-wrapper">

   <div class="toolpick header-wishlist">
            <div class="toolpick-ico" data-bind="scope: 'wishlist'">
              <a href="<?php echo $this->getBaseUrl() . 'wishlist'?>"><?php echo __('My Wish List');?>
                  <!-- ko if: wishlist().counterItems -->
                    <span data-bind="text: wishlist().counterItems, css: {'active': wishlist().counterItems}" class="wishlistcount" ></span>
                  <!-- /ko -->
              </a>
                <div class="toolpick-text"><?php echo __('Wish List');?></div>
          </div>
           <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "wishlist": {
                                "component": "Magento_Wishlist/js/view/wishlist"
                            }
                        }
                    }
                }
            }
           </script>
   </div>
	<?php //if(!$customerSession->isLoggedIn()) :?>
		<a <?php  if ($isLoggedIn): ?> style="display:none" <?php endif; ?> class="action showcart seller-sign-up" href="<?php echo /*"https://info.tradesquare.com.au/join-tradesquare-wholesale";*/$block->getUrl('seller') ;?>">
			<span class="text"><span class="df-text"></span><span class="hidden"><?php /* @escapeNotVerified */
                    echo __('My Cart'); ?></span>
	        </span>
	    	<span class="counter">Sell with us</span>
	    </a>
	<?php //else :?>
		<a <?php  if (!$isLoggedIn): ?> style="display:none" <?php endif; ?> class="action showcart mincart" href="<?php /* @escapeNotVerified */
        echo $block->getShoppingCartUrl(); ?>"
	       data-bind="scope: 'minicart_content'">
	        <span class="text"><span class="df-text"><?php /* @escapeNotVerified */
                    //echo __('Shopping Cart');?></span><span class="hidden"><?php /* @escapeNotVerified */
                    echo __('My Cart'); ?></span>
	        </span>
	        <span class="counter qty empty"
	              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">

	            <!-- ko if: getCartParam('summary_count') -->
	            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
	            <!-- /ko -->

	            <!-- ko ifnot: getCartParam('summary_count') -->
					<span class="counter-number">0</span>
	            <!-- /ko -->

	            <span class="counter-label">
				    <!-- ko if: getCartParam('summary_count') -->
	                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
	                <!-- ko i18n: 'items' --><!-- /ko -->
	                <!-- /ko -->

	                <!-- ko ifnot: getCartParam('summary_count') -->
	                <!-- ko i18n: '0' --><!-- /ko -->
	                <!-- ko i18n: 'item' --><!-- /ko -->
	                <!-- /ko -->
	            </span>

	            <!-- ko if: getCartParam('summary_count') -->
	            <span class="price-minicart">
	                <!-- ko foreach: getRegion('subtotalContainer') -->
	                <!-- ko template: getTemplate() --><!-- /ko -->
	                <!-- /ko -->
	            </span>
	            <!-- /ko -->

	            <!-- ko ifnot: getCartParam('summary_count') -->
	            <span class="price-minicart">
	                <div class="subtotal">
	                    <div class="amount price-container">
	                        <span class="price-wrapper">
	                            <span class="price"><?php echo $priceEmpty; ?></span>
	                        </span>
	                    </div>
	                </div>
	            </span>
	            <!-- /ko -->
	        </span>
	    </a>
	    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
	        <div class="block block-minicart empty"
	             data-role="dropdownDialog"
	             data-mage-init='{"dropdownDialog":{
	                "appendTo":"[data-block=minicart]",
	                "triggerTarget":".showcart",
	                "timeout": "2000",
	                "closeOnMouseLeave": false,
	                "closeOnEscape": true,
	                "triggerClass":"active",
	                "parentClass":"active",
	                "buttons":[]}}'>
	            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
	                <!-- ko template: getTemplate() --><!-- /ko -->
	            </div>
	            <?php echo $block->getChildHtml('minicart.addons'); ?>
	        </div>
	    <?php endif ?>
    <?php //endif;?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
        echo $block->getJsLayout(); ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */
        echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>


