<?php
/**
 * Retailplace_MiraklSeller
 *
 * @copyright   Copyright © 2021 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author      Satish Gumudavelly <satish@kipanga.com.au>
 */
/**
 * @var Magento\Framework\View\Element\Template $block
 */
?>
<script type="text/x-magento-init">
    {
        "*" :
        {
            "Retailplace_MiraklSeller/js/seller_page" : { }
        }
    }
</script>

