<?php
/**
 * Retailplace_MiraklSeller
 *
 * @copyright   Copyright (c) 2021 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author      Satish Gumudavelly <satish@kipanga.com.au>
 * @author      Dmitriy Fionov <dmitriy@tradesquare.com.au>
 * @author      Alexander Korsun <aleksandr@tradesquare.com.au>
 * @author      Evgeniy Derevyanko <evgeniy@tradesquare.com.au>
 */

/** @var \Retailplace\ChannelPricing\Block\Product\ListProduct $block */
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$sellerId = $this->getRequest()->getParam('id');
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config = $this->helper('Sm\Market\Helper\Data');
$homeStyle = $_config->getThemeLayout('home_style');
$sellerHelper = $this->helper('Retailplace\MiraklSeller\Helper\Data');
$miraklFrontendDemoHelper = $this->helper('Retailplace\MiraklFrontendDemo\Helper\Data');
/** @var \Retailplace\CustomerAccount\Helper\ApprovalContext $approvalHelper */
$approvalHelper = $this->helper('Retailplace\CustomerAccount\Helper\ApprovalContext');
?>
<?php
$bestsellerLabel = $this->helper('Retailplace\Bestsellerlabel\Helper\Bestsellerlabel');
$sellerBlock = $block->getChildBlock('freeshiping.listing.seller');
$query = $this->getRequest()->getParam('q');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= __('Your search for "%1" did not match any products.', $query) ?></div>
        <div><?= __('<a href="%1?"><i>Clear Search</i></a>', $this->getUrl('marketplace/shop/view', ['id' => $sellerId])) ?></div>
    </div>
<?php else: ?>
    <div class="toolbar-top">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?= $block->getAdditionalHtml() ?>
    <?php if ($block->getMode() == 'grid'):
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    else:
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    endif;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-product products wrapper <?= $viewMode; ?> products-<?= $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php $offer = $_product->getData('main_offer'); ?>
                <?php $shop = $_product->getData('shop'); ?>
                <li class="item product product-item">
                    <div class="product-item-info <?php if (!$sellerHelper->checkIsCustomerLoggedIn() || !$approvalHelper->checkIsApproval()): ?>signup_button_bg<?php endif; ?>" data-container="product-<?= $viewMode ?>">
                        <div class="all-label all-label-top">
                            <?= $miraklFrontendDemoHelper->getCalculatedMargin($_product); ?>
                            <?php if ($_product->getData('is_businesses')): ?>
                                <div class="retail-business-label">
                                    <div class="is_businesses_label">
                                        <span><?php echo __('FOR TRADE'); ?></span>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        $position = ($pos != null) ? ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"' : '';
                        ?>
                        <?php // Product Image?>

                        <div class="image-grid">
                            <a href="<?= /* @escapeNotVerified */
                            $this->getUrl('seller/') . $sellerId . '/' . $_product->getUrlKey() . '.html' ?>" class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                        </div>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php if ($sellerHelper->checkIsCustomerLoggedIn()): ?>
                                            <a class="action tocart primary"
                                               title="<?= $block->escapeHtml(__('View Details')) ?>"
                                               href="<?= /* @escapeNotVerified */
                                               $this->getUrl('seller/') . $sellerId . '/' . $_product->getUrlKey() . '.html' ?>">
                                                <span><?= /* @escapeNotVerified */
                                                        __('View Details') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>

                                <div data-role="add-to-links"
                                     class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($_config->getAdvanced('show_wishlist_button')): ?>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#" class="action towishlist <?= "wishlist" . $_product->getId(); ?>"
                                               title="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?= $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist" role="button">
                                                <span><?= __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    <?php endif; ?>

                                    <?php if ($_config->getAdvanced('show_compare_button')): ?>
                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                        <a href="#" class="action tocompare"
                                           title="<?= $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?= $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?= $compareHelper->getPostDataParams($_product); ?>' role="button">
                                            <span><?= __('Add to Compare') ?></span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription): ?>
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */
                                    $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */
                                    $this->getUrl('seller/') . $sellerId . '/' . $_product->getUrlKey() . '.html' ?>" title="<?= /* @escapeNotVerified */
                                    $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */
                                       __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                        <?php if ($_product->getData('best_seller')): ?>
                            <div class="bestseller-label">
                                <span><?= __('Best Seller'); ?></span>
                            </div>
                        <?php endif; ?>
                        <!--LABEL PRODUCT-->
                        <?php
                        $orgPrice = (float) $_product->getPrice();
                        $fnPrice = (float) $_product->getFinalPrice();
                        ?>
                        <?php if ($_config->getAdvanced('show_salelabel') && $fnPrice < $orgPrice): ?>
                            <div class="label-product label-sale">
                                        <span class="sale-product-icon">
                                            <?= __('Sale'); ?>
                                        </span>
                            </div>
                        <?php endif; ?>
                        <?php if (!$_product->getIsSalable() && $_product->getTypeId() == 'simple'): ?>
                            <div class="out-of-stock">
                                <div class="out-off-stock-img">
                                    <img src="<?php echo $_config->getMediaUrl() . "wysiwyg/out_off_stock.png"; ?>" alt=""/>
                                </div>
                                <span class="lable"><?php echo __('Coming Soon'); ?></span>
                            </div>
                        <?php endif; ?>

                        <!--END LABEL PRODUCT-->
                        <div class="all-label">
                            <?php if ($offer): ?>
                                <?php
                                $price = null;
                                $originPrice = null;
                                $additionalInfoclearance = '';

                                $price = $offer->getPrice();
                                $originPrice = $offer->getOriginPrice();
                                $checkClearance = $offer->getClearance();
                                $minimum = $offer->getMinOrderQuantity();
                                ?>
                                <?php if (($price < $originPrice) && $checkClearance == 1): ?>
                                    <div class="sale-label">
                                        <span><?= __('Clearance'); ?></span>
                                    </div>
                                <?php elseif ($price < $originPrice): ?>
                                    <div class="sale-label">
                                        <span><?= __('Sale'); ?></span>
                                    </div>
                                <?php elseif ($checkClearance == 1): ?>
                                    <div class="sale-label">
                                        <span><?= __('Clearance'); ?></span>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php
                            $madeInAu = $_product->getMadeInAu();
                            $designedInAu = $_product->getDesignedInAu();
                            ?>
                            <?php if ($madeInAu): ?>
                                <div class="design-by-label">
                                    <span><?= __('Made In AU'); ?></span>
                                </div>
                            <?php elseif ($designedInAu): ?>
                                <div class="design-by-label">
                                    <span><?= __('Designed In AU'); ?></span>
                                </div>
                            <?php endif; ?>

                            <?php if ($sellerHelper->isProductNew($_product) && $_config->getAdvanced('show_newlabel')): ?>
                                <div class="new-label">
                                    <span><?= __('New'); ?></span>
                                </div>
                            <?php endif; ?>
                            <?php if ($block->productIsAuPostExclusive($_product)): ?>
                                <div class="au-post-exclusive-label">
                                    <span><?= __($block->getAuPostExclusiveLabel()); ?></span>
                                </div>
                            <?php endif; ?>

                            <?php if ($block->productIsNlnaExclusive($_product)): ?>
                                <div class="nlna-exclusive-label">
                                    <span><?= __($block->getNlnaExclusiveLabel()); ?></span>
                                </div>
                            <?php endif; ?>
                            <?php if ($block->productIsOpenDuringXmas($_product)): ?>
                                <div class="open-during-xmas-label">
                                    <span><?= __($block->getOpenDuringXmasLabel()); ?></span>
                                </div>
                            <?php endif; ?>
                            <?php if ($block->productShopIsClosed($_product)): ?>
                                <div class="closed-to-label">
                                    <span><?= __($block->getClosedShopLabel($_product)); ?></span>
                                </div>
                            <?php endif; ?>
                            <?php if ($offer): ?>
                                <?php if ($sellerBlock): ?>
                                    <?= $sellerBlock->setShopId($sellerId)->setProduct($_product)->toHtml() ?>
                                <?php endif; ?>
                            <?php endif; ?>

                        </div>
                        <div class="product-detial-bg">
                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */
                                       $this->getUrl('seller/') . $sellerId . '/' . $_product->getUrlKey() . '.html' ?>">
                                        <?= /* @escapeNotVerified */
                                        $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?php if (!$sellerHelper->checkIsCustomerLoggedIn()): ?>
                                    <div class="seller-info"></div>
                                <?php endif; ?>

                                <?php if ($_product->getIsSalable()): ?>
                                    <?= $block->getProductPrice($_product) ?>
                                <?php endif; ?>
                                <?php if ($offer): ?>
                                    <?= $miraklFrontendDemoHelper->getMinimumQtyHtml($_product, $minimum); ?>
                                <?php endif; ?>
                                <?= $block->getProductDetailsHtml($_product) ?>
                                <?php if (!$sellerHelper->checkIsCustomerLoggedIn()): ?>
                                    <div class="seller-info mobile-view"></div>
                                <?php endif; ?>
                            </div>
                            <div class="product details product-item-details hover">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */
                                       $this->getUrl('seller/') . $sellerId . '/' . $_product->getUrlKey() . '.html' ?>">
                                        <?= /* @escapeNotVerified */
                                        $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>

                                <?php if (!$sellerHelper->checkIsCustomerLoggedIn()): ?>
                                    <div class="seller-info"></div>
                                <?php endif; ?>

                                <?php if ($_product->getIsSalable()): ?>
                                    <?= $block->getProductPrice($_product) ?>
                                <?php endif; ?>
                                <?php if ($offer): ?>
                                    <?= $miraklFrontendDemoHelper->getMinimumQtyHtml($_product, $minimum); ?>
                                <?php endif; ?>

                                <?= $block->getProductDetailsHtml($_product) ?>
                                <div class="seller-info">
                                    <a href="<?= /* @escapeNotVerified */
                                    $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */
                                    $_productNameStripped ?>"
                                       class="action more product-url"></a>
                                    <?php if ($shop): ?>
                                        <?php
                                        $additionalInfo = $shop->getAdditionalInfo();
                                        $shopName = $shop->getName();
                                        ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="seller-name">
                                                <?= __("By %1", $shopName) ?>
                                            </div>
                                            <?php $minOrderAmount = $shop->getData('min-order-amount'); ?>
                                            <?php if ($minOrderAmount > 0): ?>
                                                <div class="mimum-order">
                                                    <?= __('%1 Minimum', $sellerHelper->formatPrice($minOrderAmount)) ?>
                                                </div>
                                            <?php else: ?>
                                                <div class="mimum-order">
                                                    <?= __('No Minimum'); ?>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>
