<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_CustomerAttributes
 */
?>
<?php

// @codingStandardsIgnoreFile

?>
<?php
/* @var $block \Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element */
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note" id="' . $element->getId() . '-note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox admin__control-checkbox' || $element->getExtType() == 'radio admin__control-radio';
$addOn = ($element->getBeforeElementHtml() || $element->getAfterElementHtml()) && !$element->getNoWrapAsAddon();
$fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId())
    . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');
?>

<?php if (!$element->getNoDisplay()): ?>
<?php if ($element->getType() == 'hidden'): ?>
    <?php echo $element->getElementHtml() ?>
<?php else: ?>
<?php if ($element->getId() == "Mobile")  { ?>
<div class="second-step">
    <?php }elseif ($element->getId() == 'business_size') { ?>
    <div class="third-step">
        <span class="number-3">3</span>
    <?php }elseif ($element->getId() == 'tradesquare') { ?>
        <div class="fourth-step">
            <span class="number-4">4</span>
    <?php }elseif ($element->getId() == 'industry') { ?>
        <div class="fifth-step">
                <span class="number-5">5</span>
    <?php }elseif ($element->getId() == 'sell_goods') { ?>
        <div class="six-step">
            <span class="number-6">6</span>
    <?php }elseif ($element->getId() == 'currently_goods_online') { ?>
    <div class="seventh-step">
        <span class="number-7">7</span>
    <?php }elseif ($element->getId() == 'sell_goods_offline') { ?>
    <div class="eigth-step">
     <span class="number-8">8</span>
    <?php } else { ?>
        <div class="">
    <?php } ?>
            <div<?php /* @escapeNotVerified */
            echo $fieldAttributes ?>>
                <?php if ($elementBeforeLabel): ?>
                    <?php echo $element->getElementHtml() ?>
                    <?php echo $element->getLabelHtml() ?>
                    <?php /* @escapeNotVerified */
                    echo $note ?>
                <?php else: ?>
                    <?php echo $element->getLabelHtml() ?>
                    <div class="admin__field-control control">
                        <?php /* @escapeNotVerified */
                        echo ($addOn) ? '<div class="admin__field">' . $element->getElementHtml() . '</div>' : $element->getElementHtml(); ?>
                        <?php /* @escapeNotVerified */
                        echo $note ?>
                    </div>
                <?php endif; ?>
                <?php if ($element->getScopeLabel()): ?>
                    <div class="field-service" value-scope="<?php /* @escapeNotVerified */
                    echo $element->getScopeLabel() ?>">
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <?php endif; ?>
        <?php endif; ?>
