<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product              = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper         = $this->helper('Magento\Catalog\Helper\Product\Compare');
$_config               = $this->helper('Sm\Market\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$productids[] = $_product->getId();
?>

<div class="product-addto-links" data-role="add-to-links">
    <?php if ($_config->getAdvanced('show_wishlist_button') && $customerSession->isLoggedIn() ) { ?>
        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
            <a href="#" class="action towishlist <?php echo "wishlist".$_product->getId();?>"
               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
               data-post='<?php /* @escapeNotVerified */
               echo $block->getAddToWishlistParams($_product); ?>'
               data-action="add-to-wishlist" role="button">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Add to Wish List') ?></span>
            </a>
        <?php endif; ?>
    <?php } ?>

    <?php if ($_config->getAdvanced('show_compare_button') && $customerSession->isLoggedIn() ) { ?>
        <a title="<?php echo __('Add to Compare'); ?>" href="#" data-post='<?php /* @escapeNotVerified */
        echo $compareHelper->getPostDataParams($_product); ?>' data-role="add-to-links" class="action tocompare">
			<span><?php /* @escapeNotVerified */
                echo __('Add to Compare') ?></span>
        </a>
    <?php } ?>
</div>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */
    echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions()) ?>
        }
    }


</script>
<script>
    require(
        [
            'jquery',
            'jquery/ui'
        ],
        function(
            $
        ) {
            $(document).ready(function(){
                setTimeout(function() {
                    $(".page-title .base").html("<span class='name-tag'>"+$(".page-title .base").html()+"</span>");
                    $(".product-addto-links").appendTo(".page-title .base");
                }, 1000);
            });
        }
    );
</script>
