<?php
/**
 * @category   Retailplace
 * @package    Retailplace_Landingpage
 * @author     ishvarmagento@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Retailplace\Landingpage\Model\ResourceModel\Landingpage;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'landingpage_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Retailplace\Landingpage\Model\Landingpage',
            'Retailplace\Landingpage\Model\ResourceModel\Landingpage'
        );
    }
}