<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
?>


<?php if($customerSession->isLoggedIn()):?>
	<a href="#" class="my_account_link"><i class="fa fa-user-o" aria-hidden="true"></i></a>
	<ul class="account_dropdown">
   	
	<li>
	<a class="signup_link_bg my_account_link" href="<?php echo $this->getBaseUrl().'customer/account/';?>">
		<?php echo __('My Account');?>
	</a>
	</li>
	<li>
	<a class="login_link_bg my_order_link" href="<?php echo $this->getBaseUrl().'sales/order/history/';?>">
		<?php echo __('My Orders');?>
	</a>
	</li>
	
	<li>
	<a class="login_link_bg my_wishlist_link" href="<?php echo $this->getBaseUrl().'wishlist/';?>">
		<?php echo __('My Wish List');?>
	</a>
	</li>

	<li>
	<a class="login_link_bg account_info_link" href="<?php echo $this->getBaseUrl().'customer/account/edit/';?>">
		<?php echo __('Account Information');?>
	</a>
	</li>

	<li>
	<a class="login_link_bg product_reivew_link" href="<?php echo $this->getBaseUrl().'review/customer/';?>">
		<?php echo __('My Product Reviews');?>
	</a>
	</li>

	<li>
	<a class="login_link_bg signout_link" href="<?php echo $this->getBaseUrl().'customer/account/logout/';?>">
		<?php echo __('Sign Out');?>
	</a>
	</li>

	</ul>
<?php else:?>
<?php 
	$currentUrl  = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
	$login_url = $this->getUrl('customer/account/login', array('referer' => base64_encode($currentUrl)));
?>
	<a class="login_link_bg" href="<?php echo $login_url;?>">
		<?php echo __('Login');?>
	</a>
	<a  class="signup_link_bg" id="signup-popup" href="javascript:void(0)">
		<?php echo __('Sign Up');?>
	</a>	
<?php endif;?>
<script type="text/javascript">
	 require(['jquery', 'jquery/ui'], function($){
	 	$(document).ready(function(){
	 		$(".login-sinup > a.my_account_link").click(function(){
	 			$(this).next().toggle();
	 		});
	 	});
	 });
</script>
<?php //echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Retailplace_CustomerAccount::signup-popup.phtml")->toHtml();?>
