<?php
/**
 * @category   Retailplace
 * @package    Retailplace_Landingpage
 * @author     ishvarmagento@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Retailplace\Landingpage\Block;

use Magento\Framework\View\Element\Template\Context;
use Retailplace\Landingpage\Model\LandingpageFactory;
use Magento\Cms\Model\Template\FilterProvider;

/**
 * Landingpage View block
 */
class LandingpageView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Landingpage
     */
    protected $_landingpage;
    protected $landingpageModel;
    public function __construct(
        Context $context,
        LandingpageFactory $landingpage,
        FilterProvider $filterProvider
    ) {
        $this->_landingpage = $landingpage;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        if ($landingpageModel = $this->getSingleData()) {
            $this->pageConfig->getTitle()->set(__($landingpageModel->getPageTitle()));
        }else{
            $this->pageConfig->getTitle()->set(__('Category Landing Page'));
        }
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        if ($this->landingpageModel == null) {
            $id = $this->getRequest()->getParam('id');
            $landingpage = $this->_landingpage->create();
            $singleData = $landingpage->load($id);
            if ($singleData->getLandingpageId() || $singleData['landingpage_id'] && $singleData->getStatus() == 1) {
                $this->landingpageModel =  $singleData;
            } else {
                $this->landingpageModel =  false;
            }
        }
        return $this->landingpageModel;
    }
}
