<?php
/**
 * @category   Retailplace
 * @package    Retailplace_Landingpage
 * @author     ishvarmagento@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Retailplace\Landingpage\Block;

use Magento\Framework\View\Element\Template\Context;
use Retailplace\Landingpage\Model\LandingpageFactory;
/**
 * Landingpage List block
 */
class LandingpageListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Landingpage
     */
    protected $_landingpage;
    public function __construct(
        Context $context,
        LandingpageFactory $landingpage
    ) {
        $this->_landingpage = $landingpage;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Retailplace Landingpage Module List Page'));
        
        if ($this->getLandingpageCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'retailplace.landingpage.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getLandingpageCollection()
            );
            $this->setChild('pager', $pager);
            $this->getLandingpageCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getLandingpageCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $landingpage = $this->_landingpage->create();
        $collection = $landingpage->getCollection();
        $collection->addFieldToFilter('status','1');
        //$landingpage->setOrder('landingpage_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}