<?php
/** @var \Retailplace\CustomerAccount\Block\Widget\CategoriesBuy $block */
/** @var \Retailplace\CustomerAccount\Block\Widget\BusinessType $block */
?>
<?php
$attributeCode = $block->getAttribute()->getAttributeCode();
$options = $block->getOptions();
?>
<div class="multiselect-img">
    <div class="preferences-wrap control" data-ui-id="<?= $attributeCode?>" data-mage-init='{"multiSelectionImage": {}}'>
        <h2><?= $block->getStoreLabel(); ?></h2>
        <div class="items">
            <?php foreach ($options as $option): ?>
            <?php if (!empty($option['icon'])): ?>
            <div class="item img <?php if ($option['selected']): ?>active<?php endif;?>">
                <img src="<?= $option['icon']?>" alt="<?= $block->escapeHtml($option['label'])?>">
                <?php else: ?>
                <div class="item <?php if ($option['selected']): ?>active<?php endif;?>">
                    <?php endif; ?>
                    <label for="<?= $attributeCode ?>-<?= $block->escapeHtmlAttr($option['value']); ?>">
                        <span><?= $block->escapeHtml($option['label'])?></span>
                    </label>
                    <input class="visibility-hidden <?= $block->isRequired() ? 'required-entry' : '' ?>" type="checkbox"
                        <?php if ($option['selected']): ?> checked="checked" <?php endif;?>
                           id="<?= $attributeCode ?>-<?= $block->escapeHtmlAttr($option['value']); ?>"
                           name="<?= $attributeCode ?>"
                           value="<?= $block->escapeHtmlAttr($option['value']); ?>">
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
