<?php

/**
 * Retailplace_Aghaseller
 *
 * @copyright   Copyright (c) 2022 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author      Alexander Korsun <aleksandr@tradesquare.com.au>
 * @author      Dmitriy Fionov <dmitriy@tradesquare.com.au>
 * @author      Natalia Sekulich <natalia@tradesquare.com.au>
 */

/**
 * Seller Listing Template
 *
 * @var $block \Retailplace\MiraklSeller\Block\Seller
 */
$shops = $block->getCollection();
$mediaUrl = $block->getMediaUrl();
?>
<?php if ($block->isEnabled()): ?>
    <div class="category-seller-list <?php if ($this->getRequest()->getParam('seller_view')) : ?> active <?php endif; ?>">
        <?php if ($shops->count()): ?>
            <div class="seller-bottom">
                <div class="sellerlist">
                    <ul class="seller-grid">
                        <?php /** @var \Mirakl\Core\Model\Shop $_shop */ ?>
                        <?php foreach ($shops as $_shop): ?>
                            <?php
                            $minimumOrder = $_shop->getData('min-order-amount');
                            $shopName = $_shop->getName();
                            $hasPromotion = count($_shop->getData('mirakl_promotion'));
                            $isNewShop = $block->isNewShop($_shop);
                            $hasNewProducts = $_shop->getHasNewProducts();
                            ?>
                            <li class="seller-item">
                                <div class="seller-item-info">
                                    <div class="seller-img <?php if ($block->isSlider($_shop)): ?>seller-img-slider owl-carousel owl-theme <?php endif; ?>">
                                        <?php $imageCount = 0; ?>
                                        <?php foreach ($block->getShopImages($_shop) as $key => $image): ?>
                                            <a href="<?= $_shop->getUrl() ?>" title="<?= $shopName; ?>" class="seller-images">
                                                <?php if ($imageCount === 0): ?>
                                                    <img src="<?= $image; ?>" class="no-lazy" alt="<?= $shopName; ?>"/>
                                                <?php else: ?>
                                                    <img src="" data-src="<?= $image; ?>" class="owl-lazy" alt="<?= $shopName; ?>"/>
                                                <?php endif; ?>
                                            </a>
                                            <?php $imageCount++; ?>
                                        <?php endforeach; ?>
                                    </div>
                                    <?php if ($isNewShop || $hasPromotion || $hasNewProducts): ?>
                                        <div class="all-label">
                                            <?php if ($isNewShop) : ?>
                                                <div class="new-label"><?= $block->getIsNewShopLabel() ?></div>
                                            <?php elseif ($hasNewProducts) : ?>
                                                <div class="new-label"><?= $block->getNewProductsAddedLabel() ?></div>
                                            <?php endif; ?>
                                        </div>
                                        <div class="product-seller-bg">
                                            <div class="seller-detail">
                                                <div class="seller-name">
                                                    <span class="shop-name">
                                                        <a href="<?= $_shop->getUrl(); ?>" title="<?= $shopName; ?>">
                                                            <strong><?= $this->escapeHtml($shopName) ?></strong>
                                                        </a>
                                                    </span>
                                                </div>
                                                <div class="seller-content">
                                                    <div class="minimum-order">
                                                        <?php if ($minimumOrder < 1) : ?>
                                                            <p><?= __('No Minimum'); ?></p>
                                                        <?php else: ?>
                                                            <p><?= $block->getFormatedPrice($minimumOrder) ?> <?= __('Minimum'); ?></p>
                                                        <?php endif; ?>
                                                    </div>
                                                    <?php if ($_shop->getData('agha_seller')): ?>
                                                        <div class="aghaseller-label">
                                                            <span><?= __('AGHA Member'); ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php if (count($_shop->getData('mirakl_promotion'))): ?>
                                                        <div class="seller-promotions">
                                                            <span class="promotion-block-title"><?= __('Supplier Specials') ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                            <div class="seller-detail seller-detail-hover">
                                                <div class="seller-name">
                                                    <span class="shop-name">
                                                        <a href="<?= $_shop->getUrl(); ?>" title="<?= $shopName; ?>">
                                                            <strong><?= $this->escapeHtml($shopName) ?></strong>
                                                        </a>
                                                    </span>
                                                </div>
                                                <div class="seller-content">
                                                    <div class="minimum-order">
                                                        <?php if ($minimumOrder < 1) : ?>
                                                            <p><?= __('No Minimum'); ?></p>
                                                        <?php else: ?>
                                                            <p><?= $block->getFormatedPrice($minimumOrder) ?> <?= __('Minimum'); ?></p>
                                                        <?php endif; ?>
                                                    </div>
                                                    <?php if ($_shop->getData('agha_seller')): ?>
                                                        <div class="aghaseller-label">
                                                            <span><?= __('AGHA Member'); ?></span>
                                                        </div>
                                                    <?php endif; ?>

                                                    <?php if ($hasPromotion): ?>
                                                        <div class="seller-promotions">
                                                            <span class="promotion-block-title"><?= __('Supplier Specials') ?></span>
                                                            <?php foreach ($_shop->getData('mirakl_promotion') as $sellerPromotion): ?>
                                                                <span class="seller-promotion">
                                                                    <?= $block->escapeHtml($sellerPromotion->getLocalizedPublicDescription()) ?>
                                                                </span>
                                                            <?php endforeach; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                    <?php else: ?>
                                        <div class="all-label"></div>
                                        <div class="seller-detail">
                                            <div class="seller-name">
                                                <span class="shop-name">
                                                    <a href="<?= $_shop->getUrl(); ?>" title="<?= $shopName; ?>">
                                                        <strong><?= $this->escapeHtml($shopName) ?></strong>
                                                    </a>
                                                </span>
                                            </div>
                                            <div class="seller-content">
                                                <div class="minimum-order">
                                                    <?php if ($minimumOrder < 1) : ?>
                                                            <p><?= __('No Minimum'); ?></p>
                                                    <?php else: ?>
                                                        <p><?= $block->getFormatedPrice($minimumOrder) ?> <?= __('Minimum'); ?></p>
                                                    <?php endif; ?>
                                                </div>
                                                <?php if ($_shop->getData('agha_seller')): ?>
                                                    <div class="aghaseller-label">
                                                        <span><?= __('AGHA Member'); ?></span>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
        <?php endif; ?>
            <script type="text/javascript">
                require([
                    'jquery',
                    'owlcarousel'
                ], function ($) {
                    $(".category-seller-list  .seller-img-slider").owlCarousel({
                        responsive: {
                            0: {
                                items: 1
                            },
                            480: {
                                items: 1
                            },
                            768: {
                                items: 1
                            },
                            992: {
                                items: 1
                            },
                            1200: {
                                items: 1
                            },
                        },
                        autoplay: false,
                        loop: true,
                        nav: true,
                        navRewind: false,
                        dots: true,
                        autoplayHoverPause: true,
                        margin: 10
                    });
                });
            </script>
        <?php else: ?>
            <div class="message info empty">
                <div><?= __('We can\'t find Suppliers matching the selection.') ?></div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
