<?php
/**
 * @category   Retailplace
 * @package    Retailplace_Landingpage
 * @author     ishvarmagento@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Retailplace\Landingpage\Model\ResourceModel;

class Landingpage extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('retailplace_landingpage', 'landingpage_id');   //here "retailplace_landingpage" is table name and "landingpage_id" is the primary key of custom table
    }
}