<?php

/**
 * Retailplace_Stripe
 *
 * @copyright   Copyright (c) 2021 TRADESQUARE PTY LTD (www.tradesquare.com.au)
 * @author      Evgeniy Derevyanko <evgeniy@tradesquare.com.au>
 * @author      Ruslan Mukhatov <ruslan@tradesquare.com.au>
 */

/** @var $block \Magento\Sales\Block\Order\Info */
$_order = $block->getOrder();
?>
<div class="order-date order-payment-date">
    <span class="label"><?= __("Payment Date"); ?>: </span>
    <span class="date">
        <?= $_order->getPaymentDate() ?
            $block->formatDate($_order->getPaymentDate()) :
            $block->formatDate($_order->getCreatedAt()) ?>
    </span>
</div>
